/**
 * MYSTICOS — Semantic Profiles for 78 Rider-Waite-Smith Tarot Cards
 * Pure Semantic Data (Themes, Dynamics, Constructive, Shadow).
 * NO canned prose paragraphs. 100% Deterministic Knowledge Base.
 */

import { SemanticProfile } from '@mystic/core';

export interface TarotSemanticProfile extends SemanticProfile {
  arcana: 'MAJOR' | 'MINOR';
  rank: number;
  suit?: 'WANDS' | 'CUPS' | 'SWORDS' | 'PENTACLES';
  element: 'FIRE' | 'WATER' | 'AIR' | 'EARTH';
}

export const TAROT_SEMANTIC_PROFILES: Record<string, TarotSemanticProfile> = {
  MAJOR_00_FOOL: {
    id: 'MAJOR_00_FOOL',
    name: 'The Fool',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 0,
    element: 'AIR',
    themes: ["fresh_start","unlimited_potential","innocence","spontaneity"],
    dynamics: ["leap_of_faith","unconventional_path"],
    constructive: ["openness","courage","unbiased_exploration"],
    shadow: ["recklessness","naivety","folly","disregarding_warning"],
  },
  MAJOR_01_MAGICIAN: {
    id: 'MAJOR_01_MAGICIAN',
    name: 'The Magician',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 1,
    element: 'AIR',
    themes: ["conscious_will","resourcefulness","manifestation","agency"],
    dynamics: ["channeling_potential","skillful_execution"],
    constructive: ["focus","mastery","initiative","aligning_resources"],
    shadow: ["manipulation","trickery","latent_potential_unused","arrogance"],
  },
  MAJOR_02_HIGH_PRIESTESS: {
    id: 'MAJOR_02_HIGH_PRIESTESS',
    name: 'The High Priestess',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 2,
    element: 'WATER',
    themes: ["intuition","subconscious","sacred_knowledge","stillness"],
    dynamics: ["inner_attunement","patient_gestation"],
    constructive: ["intuitive_depth","equanimity","holding_mystery"],
    shadow: ["secrecy","passivity","emotional_detachment","surface_ignorance"],
  },
  MAJOR_03_EMPRESS: {
    id: 'MAJOR_03_EMPRESS',
    name: 'The Empress',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 3,
    element: 'EARTH',
    themes: ["abundance","fertility","nurturance","organic_growth"],
    dynamics: ["creative_gestation","receptive_nourishment"],
    constructive: ["generosity","sensory_appreciation","sustainable_care"],
    shadow: ["smothering","creative_block","material_dependence","neglect"],
  },
  MAJOR_04_EMPEROR: {
    id: 'MAJOR_04_EMPEROR',
    name: 'The Emperor',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 4,
    element: 'FIRE',
    themes: ["structure","authority","order","foundational_power"],
    dynamics: ["establishing_boundaries","strategic_governance"],
    constructive: ["stability","protective_leadership","systematic_execution"],
    shadow: ["authoritarianism","rigidity","inflexibility","loss_of_control"],
  },
  MAJOR_05_HIEROPHANT: {
    id: 'MAJOR_05_HIEROPHANT',
    name: 'The Hierophant',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 5,
    element: 'EARTH',
    themes: ["tradition","structured_learning","shared_values","mentorship"],
    dynamics: ["adherence_to_protocol","institutional_guidance"],
    constructive: ["ethical_grounding","lineage_wisdom","community_consensus"],
    shadow: ["dogmatism","blind_conformity","moral_rigidity","hypocrisy"],
  },
  MAJOR_06_LOVERS: {
    id: 'MAJOR_06_LOVERS',
    name: 'The Lovers',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 6,
    element: 'AIR',
    themes: ["value_alignment","partnership","conscious_choice","synergy"],
    dynamics: ["choosing_with_heart","reciprocal_integration"],
    constructive: ["deep_connection","moral_discernment","integrated_duality"],
    shadow: ["indecision","compromise_of_integrity","codependency","division"],
  },
  MAJOR_07_CHARIOT: {
    id: 'MAJOR_07_CHARIOT',
    name: 'The Chariot',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 7,
    element: 'WATER',
    themes: ["disciplined_will","triumph_over_conflict","momentum","determination"],
    dynamics: ["unifying_opposing_drives","directed_advance"],
    constructive: ["tenacity","self_control","focused_propulsion"],
    shadow: ["loss_of_direction","aggressive_domination","burnout","reckless_speed"],
  },
  MAJOR_08_STRENGTH: {
    id: 'MAJOR_08_STRENGTH',
    name: 'Strength',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 8,
    element: 'FIRE',
    themes: ["moral_courage","patient_compassion","gentle_mastery","resilience"],
    dynamics: ["taming_instinct","enduring_gentleness"],
    constructive: ["inner_fortitude","emotional_poise","empathetic_command"],
    shadow: ["self_doubt","coercive_force","uncontrolled_impulse","exhaustion"],
  },
  MAJOR_09_HERMIT: {
    id: 'MAJOR_09_HERMIT',
    name: 'The Hermit',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 9,
    element: 'EARTH',
    themes: ["solitary_reflection","inner_wisdom","prudent_guidance","discernment"],
    dynamics: ["withdrawing_to_reflect","lighting_the_path"],
    constructive: ["contemplative_depth","authenticity","patient_search_for_truth"],
    shadow: ["isolation","misanthropy","loneliness","rejection_of_support"],
  },
  MAJOR_10_WHEEL_OF_FORTUNE: {
    id: 'MAJOR_10_WHEEL_OF_FORTUNE',
    name: 'Wheel of Fortune',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 10,
    element: 'FIRE',
    themes: ["cyclical_change","turning_point","inevitability","adaptation"],
    dynamics: ["shifting_circumstances","riding_the_cycle"],
    constructive: ["flexibility","readiness_for_opportunity","philosophical_acceptance"],
    shadow: ["helplessness","resisting_cycles","gambling_on_luck","fatalism"],
  },
  MAJOR_11_JUSTICE: {
    id: 'MAJOR_11_JUSTICE',
    name: 'Justice',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 11,
    element: 'AIR',
    themes: ["karmic_law","objective_truth","impartial_fairness","equilibrium"],
    dynamics: ["weighing_consequences","restoring_balance"],
    constructive: ["lucid_discernment","ethical_integrity","accountability"],
    shadow: ["harsh_judgement","bias","evasion_of_consequences","legalistic_coldness"],
  },
  MAJOR_12_HANGED_MAN: {
    id: 'MAJOR_12_HANGED_MAN',
    name: 'The Hanged Man',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 12,
    element: 'WATER',
    themes: ["voluntary_pause","inverted_perspective","surrender","metamorphosis"],
    dynamics: ["suspending_action","seeing_from_reverse"],
    constructive: ["letting_go_of_ego","paradoxical_insight","patient_gestation"],
    shadow: ["martyrdom","stagnation","stubborn_resistance","futile_sacrifice"],
  },
  MAJOR_13_DEATH: {
    id: 'MAJOR_13_DEATH',
    name: 'Death',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 13,
    element: 'WATER',
    themes: ["profound_transition","closing_cycles","inevitable_clearance","rebirth"],
    dynamics: ["shedding_the_obsolete","clearing_soil_for_the_new"],
    constructive: ["graceful_release","regeneration","irreversible_growth"],
    shadow: ["fear_of_loss","clinging_to_the_past","decay_without_renewal","denial"],
  },
  MAJOR_14_TEMPERANCE: {
    id: 'MAJOR_14_TEMPERANCE',
    name: 'Temperance',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 14,
    element: 'FIRE',
    themes: ["synthesis_of_opposites","alchemy","measured_moderation","harmony"],
    dynamics: ["blending_polarities","calibrated_integration"],
    constructive: ["equipoise","patience","healing_through_compromise"],
    shadow: ["imbalance","excess","clashing_extremes","lack_of_moderation"],
  },
  MAJOR_15_DEVIL: {
    id: 'MAJOR_15_DEVIL',
    name: 'The Devil',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 15,
    element: 'EARTH',
    themes: ["material_entanglement","shadow_impulses","illusory_bondage","compulsion"],
    dynamics: ["facing_unconscious_chains","recognizing_self_deception"],
    constructive: ["integrating_shadow","confronting_taboo","pragmatic_instinct"],
    shadow: ["addiction","obsession","toxic_attachment","victim_mentality"],
  },
  MAJOR_16_TOWER: {
    id: 'MAJOR_16_TOWER',
    name: 'The Tower',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 16,
    element: 'FIRE',
    themes: ["structural_disruption","sudden_change","forced_reassessment","liberation"],
    dynamics: ["collapse_of_illusion","breakdown_before_breakthrough"],
    constructive: ["releasing_false_security","radical_honesty","rapid_clearing"],
    shadow: ["shock","resistance_to_collapse","destructive_denial","instability"],
  },
  MAJOR_17_STAR: {
    id: 'MAJOR_17_STAR',
    name: 'The Star',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 17,
    element: 'AIR',
    themes: ["renewal_of_hope","serenity","unconditional_faith","inspiration"],
    dynamics: ["replenishing_the_spirit","calm_after_the_storm"],
    constructive: ["optimism","authenticity","vulnerability","creative_guidance"],
    shadow: ["hopelessness","discouragement","unrealistic_daydreaming","disillusion"],
  },
  MAJOR_18_MOON: {
    id: 'MAJOR_18_MOON',
    name: 'The Moon',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 18,
    element: 'WATER',
    themes: ["subconscious_shadows","uncertainty","deception","symbolic_dreamwork"],
    dynamics: ["navigating_murky_waters","facing_primordial_fears"],
    constructive: ["heightened_intuition","creative_depth","unmasking_illusions"],
    shadow: ["paranoia","confusion","disorientation","distorted_perception"],
  },
  MAJOR_19_SUN: {
    id: 'MAJOR_19_SUN',
    name: 'The Sun',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 19,
    element: 'FIRE',
    themes: ["conscious_vitality","lucid_clarity","joyful_success","wholeness"],
    dynamics: ["radiating_vital_energy","full_manifestation"],
    constructive: ["warmth","transparency","generous_celebration","unclouded_truth"],
    shadow: ["burnout","vanity","excessive_optimism","delayed_gratification"],
  },
  MAJOR_20_JUDGEMENT: {
    id: 'MAJOR_20_JUDGEMENT',
    name: 'Judgement',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 20,
    element: 'FIRE',
    themes: ["awakening_call","reckoning","redemption","elevated_perspective"],
    dynamics: ["answering_higher_calling","integrating_life_lessons"],
    constructive: ["rebirth","liberation_from_guilt","decisive_clarity"],
    shadow: ["self_condemnation","reluctance_to_answer","denial_of_truth","lingering_regret"],
  },
  MAJOR_21_WORLD: {
    id: 'MAJOR_21_WORLD',
    name: 'The World',
    discipline: 'TAROT',
    arcana: 'MAJOR',
    rank: 21,
    element: 'EARTH',
    themes: ["completion_of_cycle","wholeness","triumph","integration"],
    dynamics: ["culminating_attainment","cosmic_synthesis"],
    constructive: ["fulfillment","harmony","mastery","holistic_understanding"],
    shadow: ["unfinished_business","fear_of_closure","stagnation_at_the_threshold","isolation"],
  },
  WANDS_01_ACE: {
    id: 'WANDS_01_ACE',
    name: 'Ace of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 1,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["creative_spark","passion","initiative","raw_power"],
    dynamics: ["igniting_action","seizing_opportunity"],
    constructive: ["bold_initiative","enthusiasm","creative_drive"],
    shadow: ["impatience","premature_launch","fizzling_out"],
  },
  WANDS_02_2: {
    id: 'WANDS_02_2',
    name: '2 of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 2,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["strategic_planning","forward_vision","expansion","choice"],
    dynamics: ["surveying_horizons","laying_groundwork"],
    constructive: ["long_range_foresight","sovereign_confidence"],
    shadow: ["fear_of_unknown","overthinking_plans","restlessness"],
  },
  WANDS_03_3: {
    id: 'WANDS_03_3',
    name: '3 of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 3,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["momentum","exploration","cooperative_expansion","anticipation"],
    dynamics: ["ships_coming_in","widening_reach"],
    constructive: ["optimistic_execution","commercial_foresight","leadership"],
    shadow: ["delays_in_return","disappointment_in_scale","overextension"],
  },
  WANDS_04_4: {
    id: 'WANDS_04_4',
    name: '4 of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 4,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["celebration","homecoming","community_harmony","milestone"],
    dynamics: ["reaping_first_fruits","anchoring_joy"],
    constructive: ["shared_success","stability","welcoming_environment"],
    shadow: ["transient_harmony","complacency","reluctance_to_leave_comfort"],
  },
  WANDS_05_5: {
    id: 'WANDS_05_5',
    name: '5 of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 5,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["healthy_rivalry","friction","competition","dynamic_struggle"],
    dynamics: ["testing_strength","clashing_viewpoints"],
    constructive: ["assertive_refinement","sharpening_skills","navigating_chaos"],
    shadow: ["petty_conflict","fruitless_bickering","unnecessary_hostility"],
  },
  WANDS_06_6: {
    id: 'WANDS_06_6',
    name: '6 of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 6,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["public_recognition","victory","acclaim","confidence"],
    dynamics: ["triumphant_stride","inspiring_others"],
    constructive: ["deserved_success","leadership_validation","morale_boost"],
    shadow: ["arrogance","fall_from_grace","empty_praise","imposter_syndrome"],
  },
  WANDS_07_7: {
    id: 'WANDS_07_7',
    name: '7 of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 7,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["standing_ground","defending_conviction","courage_against_odds"],
    dynamics: ["holding_the_high_ground","fending_off_pressure"],
    constructive: ["tenacity","resilience","unwavering_integrity"],
    shadow: ["exhaustion","paranoia","stubborn_isolation","defensiveness"],
  },
  WANDS_08_8: {
    id: 'WANDS_08_8',
    name: '8 of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 8,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["swift_movement","rapid_communication","unobstructed_flow"],
    dynamics: ["accelerating_to_target","incoming_news"],
    constructive: ["decisive_speed","clear_trajectory","high_efficiency"],
    shadow: ["hasty_errors","misdirected_haste","overwhelm_by_speed"],
  },
  WANDS_09_9: {
    id: 'WANDS_09_9',
    name: '9 of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 9,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["resilience","grit","vigilance","near_finish_line"],
    dynamics: ["defensive_preparedness","standing_vigil"],
    constructive: ["endurance","battle_tested_wisdom","protecting_assets"],
    shadow: ["defensiveness","paranoia","fatigue","refusal_to_rest"],
  },
  WANDS_10_10: {
    id: 'WANDS_10_10',
    name: '10 of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 10,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["heavy_burden","duty","overextension","cumulative_strain"],
    dynamics: ["carrying_the_load_alone","approaching_saturation"],
    constructive: ["high_responsibility","completing_obligations","tenacity"],
    shadow: ["burnout","refusal_to_delegate","crushing_oppression"],
  },
  WANDS_11_PAGE: {
    id: 'WANDS_11_PAGE',
    name: 'Page of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 11,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["curiosity","creative_enthusiasm","new_explorations","discovery"],
    dynamics: ["exploring_sparks","eager_learning"],
    constructive: ["playful_courage","open_minded_inquiry","message_of_passion"],
    shadow: ["scattered_focus","unreliable_promises","hot_tempered_hastiness"],
  },
  WANDS_12_KNIGHT: {
    id: 'WANDS_12_KNIGHT',
    name: 'Knight of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 12,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["audacious_action","fiery_pursuit","energy","adventurousness"],
    dynamics: ["charging_ahead","bold_crusade"],
    constructive: ["fearless_momentum","inspirational_zeal","pioneering_spirit"],
    shadow: ["recklessness","temperament_swings","abandoning_unfinished_tasks"],
  },
  WANDS_13_QUEEN: {
    id: 'WANDS_13_QUEEN',
    name: 'Queen of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 13,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["vibrant_charisma","radiant_confidence","warmth","sovereignty"],
    dynamics: ["magnetic_inspiration","empowering_others"],
    constructive: ["natural_authority","joyful_courage","creative_independence"],
    shadow: ["jealousy","demanding_attention","overbearing_pride"],
  },
  WANDS_14_KING: {
    id: 'WANDS_14_KING',
    name: 'King of Wands',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 14,
    suit: 'WANDS',
    element: 'FIRE',
    themes: ["visionary_leadership","masterful_command","enterprise","honor"],
    dynamics: ["marshaling_resources","pioneering_governance"],
    constructive: ["executive_vision","charismatic_conviction","inspirational_scale"],
    shadow: ["autocratic_impatience","unrealistic_standards","aggressive_will"],
  },
  CUPS_01_ACE: {
    id: 'CUPS_01_ACE',
    name: 'Ace of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 1,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["emotional_overflow","receptivity","spiritual_grace","love_spark"],
    dynamics: ["heart_opening","intuitive_attunement"],
    constructive: ["authentic_vulnerability","compassion","emotional_clarity"],
    shadow: ["emotional_overwhelm","blocked_feelings","unrequited_longing"],
  },
  CUPS_02_2: {
    id: 'CUPS_02_2',
    name: '2 of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 2,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["mutual_attraction","soulful_rapport","reciprocity","trust"],
    dynamics: ["harmonious_dialogue","shared_emotional_field"],
    constructive: ["cooperation","intimate_harmony","reconciliation"],
    shadow: ["codependency","distrust","misaligned_expectations"],
  },
  CUPS_03_3: {
    id: 'CUPS_03_3',
    name: '3 of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 3,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["communal_joy","sisterhood_brotherhood","shared_celebration"],
    dynamics: ["raising_the_cup","celebrating_solidarity"],
    constructive: ["camaraderie","collaborative_delight","mutual_support"],
    shadow: ["gossip","superficiality","overindulgence","clique_exclusion"],
  },
  CUPS_04_4: {
    id: 'CUPS_04_4',
    name: '4 of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 4,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["apathy","introspection","withdrawal","unnoticed_gift"],
    dynamics: ["disengaging_from_surroundings","internal_weariness"],
    constructive: ["necessary_detachment","recalibrating_desire","stillness"],
    shadow: ["cynicism","boredom","missing_golden_opportunities","sulking"],
  },
  CUPS_05_5: {
    id: 'CUPS_05_5',
    name: '5 of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 5,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["mourning_loss","grief","regret","salvageable_remains"],
    dynamics: ["focusing_on_spilled_cups","turning_away_from_remaining"],
    constructive: ["processing_grief","emotional_purification","eventual_acceptance"],
    shadow: ["clinging_to_sorrow","paralyzing_regret","ignoring_what_remains"],
  },
  CUPS_06_6: {
    id: 'CUPS_06_6',
    name: '6 of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 6,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["nostalgia","sweet_memories","innocent_affection","reconnection"],
    dynamics: ["revisiting_roots","giving_without_strings"],
    constructive: ["emotional_purity","healing_inner_child","kindness"],
    shadow: ["living_in_the_past","rose_colored_delusion","unwillingness_to_grow_up"],
  },
  CUPS_07_7: {
    id: 'CUPS_07_7',
    name: '7 of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 7,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["myriad_options","illusions","daydreams","discernment_needed"],
    dynamics: ["fantasizing_possibilities","confronting_smoke_and_mirrors"],
    constructive: ["creative_visionary_scope","unfiltered_imagination"],
    shadow: ["analysis_paralysis","wishful_thinking","deception_by_glamour"],
  },
  CUPS_08_8: {
    id: 'CUPS_08_8',
    name: '8 of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 8,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["conscious_departure","seeking_higher_meaning","emotional_transcendence"],
    dynamics: ["walking_away_from_comfortable","journey_under_moonlight"],
    constructive: ["spiritual_quest","courage_to_let_go","prioritizing_authenticity"],
    shadow: ["escapism","chronic_dissatisfaction","abandonment_of_duties"],
  },
  CUPS_09_9: {
    id: 'CUPS_09_9',
    name: '9 of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 9,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["emotional_satisfaction","contentment","wishes_fulfilled","sensory_ease"],
    dynamics: ["sitting_in_fulfillment","gratitude_for_abundance"],
    constructive: ["inner_peace","generous_hospitality","savoring_the_present"],
    shadow: ["smugness","self_indulgence","superficial_satisfaction"],
  },
  CUPS_10_10: {
    id: 'CUPS_10_10',
    name: '10 of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 10,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["lasting_harmony","family_wholeness","emotional_sanctuary","peace"],
    dynamics: ["rainbow_of_fulfillment","intergenerational_love"],
    constructive: ["domestic_tranquility","radiant_wellbeing","shared_belonging"],
    shadow: ["façade_of_perfection","family_strain","unrealistic_ideals"],
  },
  CUPS_11_PAGE: {
    id: 'CUPS_11_PAGE',
    name: 'Page of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 11,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["tender_intuition","poetic_sensitivity","emotional_messages"],
    dynamics: ["listening_to_the_fish_in_cup","sweet_curiosity"],
    constructive: ["creative_naivety","gentle_honesty","intuitive_gifts"],
    shadow: ["hypersensitivity","moodiness","infantile_drama"],
  },
  CUPS_12_KNIGHT: {
    id: 'CUPS_12_KNIGHT',
    name: 'Knight of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 12,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["romantic_quest","poetic_devotion","chivalry","idealism"],
    dynamics: ["offering_the_chalice","pursuing_the_vision"],
    constructive: ["diplomatic_grace","lyrical_empathy","refined_manners"],
    shadow: ["fickle_idealism","escapism","disillusionment_upon_contact_with_reality"],
  },
  CUPS_13_QUEEN: {
    id: 'CUPS_13_QUEEN',
    name: 'Queen of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 13,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["deep_empathy","intuitive_counsel","emotional_depth","serene_heart"],
    dynamics: ["holding_space_for_truth","psychic_attunement"],
    constructive: ["compassionate_wisdom","emotional_security","healing_presence"],
    shadow: ["emotional_absorption","smothering_care","martyrdom"],
  },
  CUPS_14_KING: {
    id: 'CUPS_14_KING',
    name: 'King of Cups',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 14,
    suit: 'CUPS',
    element: 'WATER',
    themes: ["emotional_mastery","calm_leadership","diplomacy","equanimity"],
    dynamics: ["ruling_turbulent_waters","balanced_compassion"],
    constructive: ["mature_temperance","counseling_ability","grace_under_pressure"],
    shadow: ["emotional_coldness","repressed_volcano","subtle_manipulation"],
  },
  SWORDS_01_ACE: {
    id: 'SWORDS_01_ACE',
    name: 'Ace of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 1,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["lucid_clarity","breakthrough_insight","intellectual_truth","surgical_cut"],
    dynamics: ["piercing_the_veil","establishing_facts"],
    constructive: ["uncompromising_honesty","mental_precision","principled_courage"],
    shadow: ["cruel_bluntness","tyranny_of_logic","intellectual_hostility"],
  },
  SWORDS_02_2: {
    id: 'SWORDS_02_2',
    name: '2 of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 2,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["stalemate","truce","blindfolded_choice","defensive_balance"],
    dynamics: ["holding_blades_crossed","blocking_external_inputs"],
    constructive: ["peaceful_pause","impartial_neutrality","holding_the_center"],
    shadow: ["willful_blindness","decision_avoidance","emotional_stonewalling"],
  },
  SWORDS_03_3: {
    id: 'SWORDS_03_3',
    name: '3 of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 3,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["heartbreak","piercing_grief","painful_truth","necessary_sorrow"],
    dynamics: ["blades_through_the_heart","clearing_illusion_through_pain"],
    constructive: ["confronting_harsh_reality","emotional_cleansing","catharsis"],
    shadow: ["wallowing_in_pain","re-traumatizing_self","cynical_bitterness"],
  },
  SWORDS_04_4: {
    id: 'SWORDS_04_4',
    name: '4 of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 4,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["sanctuary_of_mind","rest","recuperation","mental_stillness"],
    dynamics: ["laying_down_weapons","restoring_mental_reserves"],
    constructive: ["deliberate_withdrawal","meditative_clarity","convalescence"],
    shadow: ["exhaustion","forced_isolation","stagnant_retreat"],
  },
  SWORDS_05_5: {
    id: 'SWORDS_05_5',
    name: '5 of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 5,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["hollow_victory","defeat_in_battle","discord","costly_triumph"],
    dynamics: ["picking_up_spoils_of_bitter_fight","humiliating_loss"],
    constructive: ["acknowledging_limits","cutting_losses","recognizing_toxic_dynamics"],
    shadow: ["petty_vindictiveness","pyrrhic_victory","spiteful_malice"],
  },
  SWORDS_06_6: {
    id: 'SWORDS_06_6',
    name: '6 of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 6,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["transition_to_calmer_waters","passage_from_strife","mental_recovery"],
    dynamics: ["ferrying_across_rough_channel","gradual_healing"],
    constructive: ["pragmatic_relocation","leaving_trouble_behind","guided_healing"],
    shadow: ["unfinished_baggage","reluctant_departure","prolonged_drifting"],
  },
  SWORDS_07_7: {
    id: 'SWORDS_07_7',
    name: '7 of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 7,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["tactical_guile","stealth","strategy","hidden_agenda","evasion"],
    dynamics: ["taking_five_blades_quietly","outsmarting_open_confrontation"],
    constructive: ["pragmatic_resourcefulness","self_preservation","unconventional_tactics"],
    shadow: ["deceit","betrayal","evading_accountability","imposter_tactics"],
  },
  SWORDS_08_8: {
    id: 'SWORDS_08_8',
    name: '8 of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 8,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["mental_entrapment","self_imposed_restriction","perceived_helplessness"],
    dynamics: ["bound_amongst_blades","fearing_to_step_forward"],
    constructive: ["recognizing_the_bonds_are_loose","reclaiming_mental_agency"],
    shadow: ["victim_mindset","paralyzing_anxiety","resignation_to_circumstance"],
  },
  SWORDS_09_9: {
    id: 'SWORDS_09_9',
    name: '9 of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 9,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["anguish","nighttime_anxiety","sleepless_worry","guilt_or_dread"],
    dynamics: ["waking_in_the_dark","magnifying_fears_in_the_mind"],
    constructive: ["facing_worst_fears","purging_mental_poison","seeking_daylight_perspective"],
    shadow: ["catastrophizing","spiral_of_despair","unfounded_terror"],
  },
  SWORDS_10_10: {
    id: 'SWORDS_10_10',
    name: '10 of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 10,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["definitive_ending","rock_bottom","inevitable_collapse","dawn_after_darkness"],
    dynamics: ["swords_in_the_back","exhaustion_of_the_cycle"],
    constructive: ["total_release_of_struggle","the_worst_is_over","inevitable_dawn"],
    shadow: ["melodramatic_defeat","refusal_to_get_up","deep_victimization"],
  },
  SWORDS_11_PAGE: {
    id: 'SWORDS_11_PAGE',
    name: 'Page of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 11,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["vigilant_curiosity","intellectual_inquiry","alert_scout","mental_agility"],
    dynamics: ["scanning_for_anomalies","probing_arguments"],
    constructive: ["sharp_observation","truth_seeking","rapid_learning"],
    shadow: ["spying","hypercriticism","abrasive_defensiveness"],
  },
  SWORDS_12_KNIGHT: {
    id: 'SWORDS_12_KNIGHT',
    name: 'Knight of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 12,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["incisive_rush","intellectual_audacity","direct_assault_on_problems"],
    dynamics: ["riding_full_tilt_into_wind","slashing_through_fog"],
    constructive: ["fearless_clarity","decisive_action","principled_advocacy"],
    shadow: ["tactlessness","blind_ideology","leaving_collateral_damage"],
  },
  SWORDS_13_QUEEN: {
    id: 'SWORDS_13_QUEEN',
    name: 'Queen of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 13,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["sharp_discernment","intellectual_sovereignty","impartial_candor","boundaries"],
    dynamics: ["sword_upright","cutting_through_pretense"],
    constructive: ["objective_judgement","mature_independence","lucid_boundaries"],
    shadow: ["cynical_coldness","harsh_hypercriticism","vindictiveness"],
  },
  SWORDS_14_KING: {
    id: 'SWORDS_14_KING',
    name: 'King of Swords',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 14,
    suit: 'SWORDS',
    element: 'AIR',
    themes: ["commanding_intellect","ethical_justice","strategic_authority","clarity"],
    dynamics: ["pronouncing_judgement","structuring_truth"],
    constructive: ["impartial_rule","masterful_communication","unshakable_principles"],
    shadow: ["tyrannical_rigidity","emotional_sterility","ruthless_verdicts"],
  },
  PENTACLES_01_ACE: {
    id: 'PENTACLES_01_ACE',
    name: 'Ace of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 1,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["tangible_seed","material_opportunity","financial_anchor","practical_foundation"],
    dynamics: ["offering_the_coin","planting_the_seed"],
    constructive: ["grounded_pragmatism","concrete_potential","stewardship"],
    shadow: ["greed","material_fixation","missing_practical_timing"],
  },
  PENTACLES_02_2: {
    id: 'PENTACLES_02_2',
    name: '2 of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 2,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["dynamic_balance","juggling_priorities","adaptability","fluid_flow"],
    dynamics: ["navigating_ebbs_and_flows","balancing_two_coins"],
    constructive: ["dexterity","playful_flexibility","agile_resource_allocation"],
    shadow: ["overwhelm","dropping_the_ball","financial_instability"],
  },
  PENTACLES_03_3: {
    id: 'PENTACLES_03_3',
    name: '3 of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 3,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["collaborative_craft","team_mastery","benchmarking","skilled_execution"],
    dynamics: ["building_the_cathedral","consulting_with_experts"],
    constructive: ["high_workmanship","shared_standards","peer_recognition"],
    shadow: ["shoddy_work","creative_friction","unwillingness_to_learn"],
  },
  PENTACLES_04_4: {
    id: 'PENTACLES_04_4',
    name: '4 of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 4,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["conservation","holding_territory","security_boundaries","saving"],
    dynamics: ["clutching_coins_tightly","guarding_the_perimeter"],
    constructive: ["prudent_reserve","financial_discipline","preserving_capital"],
    shadow: ["miserliness","paralyzing_scarcity_mindset","possessiveness"],
  },
  PENTACLES_05_5: {
    id: 'PENTACLES_05_5',
    name: '5 of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 5,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["material_hardship","isolation","scarcity","seeking_sanctuary"],
    dynamics: ["walking_in_the_snow","passing_the_illuminated_window"],
    constructive: ["resilience_under_strain","humble_solidarity","identifying_true_priorities"],
    shadow: ["victim_mentality","pride_blocking_help","chronic_poverty_mindset"],
  },
  PENTACLES_06_6: {
    id: 'PENTACLES_06_6',
    name: '6 of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 6,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["calibrated_generosity","reciprocity","resource_sharing","equitable_distribution"],
    dynamics: ["weighing_the_scales","distributing_to_those_in_need"],
    constructive: ["generous_stewardship","balanced_exchange","gratitude_in_receiving"],
    shadow: ["conditional_charity","patronizing_power","debt_entanglement"],
  },
  PENTACLES_07_7: {
    id: 'PENTACLES_07_7',
    name: '7 of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 7,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["investment","patience","assessment","long_term","harvest"],
    dynamics: ["pause_and_evaluate","continue_or_adjust"],
    constructive: ["patience","long_term_thinking","systematic_review","pragmatic_pacing"],
    shadow: ["impatience","sunk_cost","frustration","premature_abandonment"],
  },
  PENTACLES_08_8: {
    id: 'PENTACLES_08_8',
    name: '8 of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 8,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["dedicated_apprenticeship","diligence","continuous_refinement","craftsmanship"],
    dynamics: ["hammering_coin_by_coin","honing_detail"],
    constructive: ["meticulous_mastery","focused_discipline","quality_pride"],
    shadow: ["perfectionism","meaningless_toil","losing_forest_for_the_trees"],
  },
  PENTACLES_09_9: {
    id: 'PENTACLES_09_9',
    name: '9 of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 9,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["self_sufficiency","graceful_abundance","discernment","earned_solitude"],
    dynamics: ["walking_the_cultivated_vineyard","relishing_autonomy"],
    constructive: ["financial_independence","refined_taste","dignified_peace"],
    shadow: ["isolation_behind_wealth","fear_of_dependence","ostentation"],
  },
  PENTACLES_10_10: {
    id: 'PENTACLES_10_10',
    name: '10 of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 10,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["generational_legacy","enduring_wealth","family_dynasty","rooted_prosperity"],
    dynamics: ["anchoring_the_estate","honoring_tradition_and_descendants"],
    constructive: ["long_range_solidity","community_roots","sustainable_wealth"],
    shadow: ["disputes_over_inheritance","stifling_tradition","material_entrapment"],
  },
  PENTACLES_11_PAGE: {
    id: 'PENTACLES_11_PAGE',
    name: 'Page of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 11,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["practical_curiosity","studious_application","grounded_ambition","apprentice"],
    dynamics: ["inspecting_the_coin","building_tangible_competence"],
    constructive: ["reliable_diligence","thirst_for_practical_skill","dependability"],
    shadow: ["procrastination","sluggishness","lack_of_follow_through"],
  },
  PENTACLES_12_KNIGHT: {
    id: 'PENTACLES_12_KNIGHT',
    name: 'Knight of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 12,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["methodical_persistence","unshakable_duty","thoroughness","patience"],
    dynamics: ["steady_tilling_of_the_field","unhurried_progress"],
    constructive: ["iron_reliability","unwavering_work_ethic","meticulous_execution"],
    shadow: ["inflexible_stubbornness","workaholism","resistance_to_innovation"],
  },
  PENTACLES_13_QUEEN: {
    id: 'PENTACLES_13_QUEEN',
    name: 'Queen of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 13,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["practical_nurturance","sensory_grounding","resourceful_hospitality","earthy_grace"],
    dynamics: ["tending_the_garden","creating_comfort_and_security"],
    constructive: ["generous_capability","pragmatic_wisdom","harmonious_living"],
    shadow: ["material_smothering","anxiety_over_resources","neglect_of_self"],
  },
  PENTACLES_14_KING: {
    id: 'PENTACLES_14_KING',
    name: 'King of Pentacles',
    discipline: 'TAROT',
    arcana: 'MINOR',
    rank: 14,
    suit: 'PENTACLES',
    element: 'EARTH',
    themes: ["material_sovereignty","enterprise_builder","financial_mastery","stability"],
    dynamics: ["governing_the_estate","compounding_prosperity"],
    constructive: ["generous_leadership","unflappable_reliability","commercial_acumen"],
    shadow: ["ruthless_greed","stubborn_materialism","measuring_value_only_by_wealth"],
  },
};
