/**
 * MYSTICOS — Semantic Profiles for Pythagorean Numerology
 * Pure Semantic Data (Themes, Dynamics, Constructive, Shadow).
 * Numbers 1-9, Master Numbers 11, 22, 33.
 * NO canned prose paragraphs. 100% Deterministic Knowledge Base.
 */

import { SemanticProfile } from '@mystic/core';

export interface NumerologyNumberSemanticProfile extends SemanticProfile {
  number: number;
  plane: 'PHYSICAL' | 'EMOTIONAL' | 'MENTAL' | 'SPIRITUAL';
  rulingArchetype: string;
}

export const NUMEROLOGY_NUMBER_PROFILES: Record<number, NumerologyNumberSemanticProfile> = {
  1: {
    id: 'NUM_1',
    name: 'Số 1 — Người Tiên Phong',
    number: 1,
    discipline: 'NUMEROLOGY',
    plane: 'MENTAL',
    rulingArchetype: 'The Pioneer / Leader',
    themes: ['tien_phong', 'doc_lap', 'y_chi_tu_chu', 'khoi_nghiep', 'sang_tao_nguyen_ban'],
    dynamics: ['tu_luc_canh_sinh', 'mo_loi_di_rieng', 'dan_dau_hanh_dong'],
    constructive: ['ban_linh_quyet_doan', 'quang_minh_chinh_truc', 'tam_nhin_khoi_xuong', 'khi_phach_kien_cuong'],
    shadow: ['tu_phu_doc_doan', 'co_doc_xa_lanh', 'nong_voi_ap_dat', 'so_that_bai'],
  },
  2: {
    id: 'NUM_2',
    name: 'Số 2 — Người Hòa Giải & Trực Giác',
    number: 2,
    discipline: 'NUMEROLOGY',
    plane: 'EMOTIONAL',
    rulingArchetype: 'The Peacemaker / Diplomat',
    themes: ['hoa_hop', 'lang_nghe', 'truc_giac', 'ngoai_giao', 'dong_hanh'],
    dynamics: ['ket_noi_doi_thoai', 'dung_hoa_mau_thuan', 'nuoi_duong_tinh_cam'],
    constructive: ['thau_cam_sau_sac', 'kheo_leo_nhu_thuan', 'kien_nhan_cho_che', 'trung_thanh_tin_cay'],
    shadow: ['phu_thuoc_cam_xuc', 'do_du_thieu_quyet_doan', 'de_bi_ton_thuong', 'ne_tranh_xung_dot'],
  },
  3: {
    id: 'NUM_3',
    name: 'Số 3 — Người Sáng Tạo & Truyền Cảm Hứng',
    number: 3,
    discipline: 'NUMEROLOGY',
    plane: 'MENTAL',
    rulingArchetype: 'The Creative / Communicator',
    themes: ['sang_tao', 'ngon_ngu', 'truyen_cam_hung', 'lac_quan', 'bieu_dat_nghe_thuat'],
    dynamics: ['lan_toa_nang_luong', 'khuay_dong_khong_khi', 'bien_y_tuong_thanh_hinh_anh'],
    constructive: ['hoat_ngon_duyen_dang', 'giau_tri_tuong_tuong', 'lac_quan_yeu_doi', 'da_tai_da_nghe'],
    shadow: ['phan_tan_nang_luong', 'nong_can_hinh_thuc', 'de_thoa_hiep_cam_hung', 'loi_noi_thieu_suy_nghi'],
  },
  4: {
    id: 'NUM_4',
    name: 'Số 4 — Người Xây Nền Móng & Kỷ Luật',
    number: 4,
    discipline: 'NUMEROLOGY',
    plane: 'PHYSICAL',
    rulingArchetype: 'The Builder / Organizer',
    themes: ['ky_luat', 'thuc_tien', 'cau_truc', 'kien_tri', 'an_toan_ben_vung'],
    dynamics: ['xay_dung_be_mong', 'quy_trinh_hoa', 'tich_luy_tieu_chuan'],
    constructive: ['dang_tin_cay_sat_da', 'chuyen_nghiep_chuan_xac', 'lao_dong_can_man', 'quan_tri_rui_ro'],
    shadow: ['cung_nhac_bao_thu', 'ngai_doi_moi', 'thieu_linh_hoat', 'qua_chu_trong_chi_tiet'],
  },
  5: {
    id: 'NUM_5',
    name: 'Số 5 — Người Tự Do & Đột Phá',
    number: 5,
    discipline: 'NUMEROLOGY',
    plane: 'PHYSICAL',
    rulingArchetype: 'The Explorer / Catalyst',
    themes: ['tu_do', 'bien_hoa', 'phieu_luu', 'trai_nghiem', 'dot_pha_khuon_mau'],
    dynamics: ['thich_ung_nhanh', 'mo_rong_ranh_gioi', 'nam_bat_thoi_co_moi'],
    constructive: ['linh_hoat_tuyet_voi', 'dung_cam_doi_moi', 'ket_noi_da_van_hoa', 'khoang_dat_phong_cach'],
    shadow: ['ca_them_chong_chan', 'vo_ky_luat', 'boc_dong_thieu_ke_hoach', 'sa_da_huong_thu'],
  },
  6: {
    id: 'NUM_6',
    name: 'Số 6 — Người Nuôi Dưỡng & Trách Nhiệm',
    number: 6,
    discipline: 'NUMEROLOGY',
    plane: 'EMOTIONAL',
    rulingArchetype: 'The Nurturer / Caregiver',
    themes: ['gia_dinh', 'yeu_thuong', 'trach_nhiem', 'bao_boc', 'tham_my_hoa_hop'],
    dynamics: ['cham_soc_to_am', 'gan_ket_cong_dong', 'chua_lanh_ran_nut'],
    constructive: ['giau_long_nhan_ai', 'tinh_than_phung_su', 'gu_tham_my_am_ap', 'chuan_muc_gia_dinh'],
    shadow: ['kiem_soat_nguoi_than', 'om_dom_trach_nhiem', 'lo_lang_thai_qua', 'de_bi_loi_dung'],
  },
  7: {
    id: 'NUM_7',
    name: 'Số 7 — Nhà Chiêm Nghiệm & Tri Thức',
    number: 7,
    discipline: 'NUMEROLOGY',
    plane: 'SPIRITUAL',
    rulingArchetype: 'The Seeker / Philosopher',
    themes: ['chiem_nghiem', 'triet_hoc', 'nghien_cuu_sau', 'tinh_lang', 'truc_giac_tam_linh'],
    dynamics: ['tim_kiem_chan_ly', 'dao_sau_ban_chat', 'thanh_loc_tam_tri'],
    constructive: ['tri_tue_uyen_bac', 'phan_bien_sac_ben', 'doc_lap_noi_tam', 'cot_cach_thanh_cao'],
    shadow: ['co_lap_xa_canh', 'hoai_nghi_lanh_lung', 'khoan_dung_thieu_thuc_te', 'khap_khieng_giao_tiep'],
  },
  8: {
    id: 'NUM_8',
    name: 'Số 8 — Nhà Quản Trị & Thực Hiện Hóa',
    number: 8,
    discipline: 'NUMEROLOGY',
    plane: 'PHYSICAL',
    rulingArchetype: 'The Executive / Strategist',
    themes: ['thanh_tuu_vat_chat', 'quan_tri_vi_the', 'quyen_luc', 'nhan_qua', 'dieu_hanh'],
    dynamics: ['hien_thuc_hoa_tam_nhin', 'van_hanh_nguon_luc_lon', 'can_bang_giua_vat_chat_va_tinh_than'],
    constructive: ['nang_luc_dieu_hanh_xuat_sac', 'nhay_ben_tai_chinh', 'y_chi_sat_da', 'khi_phach_doanh_nhan'],
    shadow: ['thuc_dung_qua_muc', 'say_men_quyen_luc', 'nguy_co_pha_san_neu_mat_dao_duc', 'lanh_lung'],
  },
  9: {
    id: 'NUM_9',
    name: 'Số 9 — Người Phụng Sự & Nhân Đạo',
    number: 9,
    discipline: 'NUMEROLOGY',
    plane: 'SPIRITUAL',
    rulingArchetype: 'The Humanitarian / Sage',
    themes: ['nhan_dao', 'phung_su_cong_dong', 'buong_bo', 'tri_tue_toan_dien', 'hoan_tat_chu_ky'],
    dynamics: ['cung_hien_vi_tha', 'nang_tam_nhan_loai', 'khep_lai_qua_khu'],
    constructive: ['bao_dung_quang_dai', 'ly_tuong_nhan_van_cao_ca', 'tam_nhin_toan_cau', 'truyen_cam_hung_vi_tha'],
    shadow: ['ao_tuong_cuu_the', 'kho_buong_bo_qua_khu', 'thieu_thuc_te_tai_chinh', 'de_that_vong'],
  },
  11: {
    id: 'NUM_11',
    name: 'Số 11/2 — Bậc Thầy Trực Giác & Soi Sáng',
    number: 11,
    discipline: 'NUMEROLOGY',
    plane: 'SPIRITUAL',
    rulingArchetype: 'The Master Illuminator',
    themes: ['soi_sang', 'truc_giac_thien_bam', 'tam_linh_bac_cao', 'truyen_cam_hung_tinh_than'],
    dynamics: ['cau_noi_tam_linh', 'thuc_tinh_cong_dong', 'nhan_thong_diep_truc_giac'],
    constructive: ['nhay_ben_tam_linh_phi_thuong', 'tam_nhin_khai_sang', 'long_trac_an_sau_sac', 'suc_hut_nhiem_mau'],
    shadow: ['cang_thang_than_kinh', 'qua_tai_cam_xuc', 'hoang_mang_truoc_su_menh', 'ne_tranh_hien_thuc'],
  },
  22: {
    id: 'NUM_22',
    name: 'Số 22/4 — Bậc Thầy Kiến Tạo Di Sản',
    number: 22,
    discipline: 'NUMEROLOGY',
    plane: 'PHYSICAL',
    rulingArchetype: 'The Master Builder',
    themes: ['kien_tao_di_san', 'tam_nhin_vi_dai_thuc_te', 'chuyen_hoa_the_gioi', 'to_chuc_quy_mo_lon'],
    dynamics: ['bien_ly_tuong_thanh_cong_trinh', 'xay_dung_nen_tang_vi_dai', 'lanh_dao_chuyen_doi'],
    constructive: ['nang_luc_thuc_thi_phi_thuong', 'tam_nhin_toan_cau_thuc_te', 'kien_dinh_bat_khuat', 'di_san_truong_ton'],
    shadow: ['ap_luc_khong_lo', 'so_that_bai_quy_mo_lon', 'cung_nhac_thai_qua', 'sup_do_the_luc'],
  },
  33: {
    id: 'NUM_33',
    name: 'Số 33/6 — Bậc Thầy Chữa Lành & Tình Yêu Vô Điều Kiện',
    number: 33,
    discipline: 'NUMEROLOGY',
    plane: 'EMOTIONAL',
    rulingArchetype: 'The Master Teacher / Healer',
    themes: ['chua_lanh_nhan_loai', 'tinh_yeu_vo_dieu_kien', 'giao_duc_khai_tam', 'phung_su_toi_thuong'],
    dynamics: ['lan_toa_yeu_thuong_thuan_khiet', 'nang_do_ke_yeu', 'khai_sang_qua_long_tu_bi'],
    constructive: ['long_trac_an_vo_bo_ben', 'nang_luc_chua_lanh_tam_hon', 'hien_than_vi_tha', 'tri_tue_nguoi_thay'],
    shadow: ['tu_hy_sinh_mu_quang', 'ganh_nang_cam_xuc_cong_dong', 'kiet_suc_noi_tam', 'tu_bien_minh_thanh_nan_nhan'],
  },
};
