/**
 * MYSTICOS — Semantic Profiles for Tử Vi Đẩu Số (Stars & Palaces)
 * Authentic Nam Phái / Bắc Phái Classical Archetypes.
 * Pure Semantic Data (Themes, Dynamics, Constructive, Shadow).
 * NO canned prose paragraphs. 100% Deterministic Knowledge Base.
 */

import { SemanticProfile } from '@mystic/core';

export interface TuViStarSemanticProfile extends SemanticProfile {
  element: 'KIM' | 'MOC' | 'THUY' | 'HOA' | 'THO';
  yinYang: 'DUONG' | 'AM';
  category: 'CHINH_TINH' | 'TU_HOA' | 'LUC_SAT' | 'LUC_CAT';
}

export interface TuViPalaceSemanticProfile extends SemanticProfile {
  category: 'TAM_PHUONG_TU_CHINH' | 'LUC_THAN' | 'TAI_SAN_THE_XAC';
  coreFocus: string;
}

export const TUVI_STAR_PROFILES: Record<string, TuViStarSemanticProfile> = {
  TU_VI: {
    id: 'TU_VI',
    name: 'Tử Vi',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'THO',
    yinYang: 'DUONG',
    themes: ['de_toa', 'lanh_dao', 'uy_quyen', 'trach_nhiem', 'ton_quy'],
    dynamics: ['trung_tam_quy_tu', 'che_cho_bao_boc', 'hoach_dinh_dai_cuc'],
    constructive: ['tam_nhin_chien_luoc', 'khoan_dung_do_luong', 'phong_thai_chinh_truc', 'tao_lap_vi_the'],
    shadow: ['doc_doan', 'co_doc_dinh_cao', 'ap_dat_chu_quan', 'kho_gan'],
  },
  THIEN_CO: {
    id: 'THIEN_CO',
    name: 'Thiên Cơ',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'MOC',
    yinYang: 'AM',
    themes: ['muu_luoc', 'tri_tue', 'bien_hoa', 'thich_ung', 'ke_hoach'],
    dynamics: ['van_dong_khong_ngung', 'phan_tich_tinh_the', 'tu_van_ho_tro'],
    constructive: ['tu_duy_sac_ben', 'ung_bien_linh_hoat', 'sang_tao_chien_luoc', 'thien_luong_ho_tro'],
    shadow: ['do_du_da_doan', 'tinh_toan_chi_li', 'tam_than_bat_dinh', 'de_mat_kien_nhan'],
  },
  THAI_DUONG: {
    id: 'THAI_DUONG',
    name: 'Thái Dương',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'HOA',
    yinYang: 'DUONG',
    themes: ['quang_minh', 'nhiet_huyet', 'cong_khai', 'danh_tieng', 'cho_che'],
    dynamics: ['toa_sang_cong_dong', 'lan_toa_nang_luong', 'thuc_thi_minh_bach'],
    constructive: ['hao_sang_chinh_truc', 'cong_hien_vi_tha', 'truyen_cam_hung', 'uy_tin_vang_xa'],
    shadow: ['nong_nay', 'hao_nhoang_ben_ngoai', 'hao_ton_suc_luc', 'tu_phu'],
  },
  VU_KHUC: {
    id: 'VU_KHUC',
    name: 'Vũ Khúc',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'KIM',
    yinYang: 'AM',
    themes: ['tai_tinh', 'quyet_doan', 'ky_luat', 'thuc_te', 'hanh_dong'],
    dynamics: ['tich_luy_tai_san', 'thuc_thi_don_doc', 'kiem_soat_nguon_luc'],
    constructive: ['quan_tri_tai_chinh', 'y_chi_sat_da', 'chuyen_mon_chuan_xac', 'doc_lap_tu_cuong'],
    shadow: ['lanh_lung_kho_tinh', 'thien_ve_vat_chat', 'co_doc', 'thieu_nhu_hoa'],
  },
  THIEN_DONG: {
    id: 'THIEN_DONG',
    name: 'Thiên Đồng',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'THUY',
    yinYang: 'DUONG',
    themes: ['phuc_tinh', 'hon_nhien', 'thich_ung', 'huong_thu', 'nhan_hau'],
    dynamics: ['bien_chuyen_tam_tinh', 'hoa_giai_tai_uong', 'cau_toan_an_lac'],
    constructive: ['tam_hon_trong_sang', 'de_gan_thien_luong', 'linh_hoat_tuy_duyen', 'phuc_duc_day_sau'],
    shadow: ['thieu_kien_dinh', 'de_thoa_hiep', 'ham_vui_chong_chan', 'ngai_kho'],
  },
  LIEM_TRINH: {
    id: 'LIEM_TRINH',
    name: 'Liêm Trinh',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'HOA',
    yinYang: 'AM',
    themes: ['chinh_khi', 'tu_trong', 'nguyen_tac', 'dam_me', 'tranh_chap'],
    dynamics: ['canh_giac_nghiem_ngat', 'giu_gin_khao_khat', 'thuc_thi_luat_le'],
    constructive: ['liem_khiet_chinh_truc', 'trung_thanh_quyet_liet', 'nang_luc_quan_tri_phap_ly', 'tu_chu_cao'],
    shadow: ['cung_nhac_gay_gat', 'danh_gia_khac_nghiet', 'de_vuong_tranh_chap', 'song_gio_tinh_cam'],
  },
  THIEN_PHU: {
    id: 'THIEN_PHU',
    name: 'Thiên Phủ',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'THO',
    yinYang: 'DUONG',
    themes: ['kho_tang', 'on_dinh', 'bao_ton', 'khoan_hoa', 'than_trong'],
    dynamics: ['quan_ly_ngan_kho', 'xay_dung_be_do', 'an_dinh_trat_tu'],
    constructive: ['bao_ton_nguon_luc', 'diem_dam_vung_vang', 'chu_dao_chu_toan', 'kinh_te_vung_chai'],
    shadow: ['an_phan_thu_thuong', 'ngai_mao_hiem', 'keo_kiet_phong_thu', 'thieu_dot_pha'],
  },
  THAI_AM: {
    id: 'THAI_AM',
    name: 'Thái Âm',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'THUY',
    yinYang: 'AM',
    themes: ['phu_quy', 'tinh_te', 'tru_tinh', 'truc_giac', 'tich_luy_am_tham'],
    dynamics: ['chuyen_hoa_ngam', 'nuoi_duong_cam_xuc', 'kiem_soat_tai_san_ngam'],
    constructive: ['nhay_ben_nghe_thuat', 'thau_hieu_tam_ly', 'quan_tri_tai_san_vung_chac', 'nhu_thuan_hoa_nha'],
    shadow: ['da_sau_da_cam', 'bi_dong_u_nghen', 'hay_lo_xa_vien_vong', 'tam_ly_bat_an'],
  },
  THAM_LANG: {
    id: 'THAM_LANG',
    name: 'Tham Lang',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'THUY',
    yinYang: 'DUONG',
    themes: ['khao_khat', 'giao_te', 'da_tai', 'bien_hoa', 'trai_nghiem'],
    dynamics: ['thu_hut_cac_moi_quan_he', 'kham_pha_linh_vuc_moi', 'theo_duoi_dam_me'],
    constructive: ['ngoai_giao_xuat_chung', 'linh_hoat_thoi_cuoc', 'sang_tao_nghe_thuat', 'cau_tien_manh_me'],
    shadow: ['tham_vong_khong_day', 'de_sa_da_cam_do', 'nong_vong_thieu_ben', 'thuc_dung'],
  },
  CU_MON: {
    id: 'CU_MON',
    name: 'Cự Môn',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'THUY',
    yinYang: 'AM',
    themes: ['ngon_ngu', 'phan_bien', 'nghi_van', 'nghien_cuu', 'khai_sang'],
    dynamics: ['chat_van_chan_ly', 'vach_tran_khuyet_diem', 'truyen_dat_thong_diep'],
    constructive: ['lap_luan_hung_bien', 'tu_duy_phan_bien_sau', 'khao_sat_chi_tiet', 'nghien_cuu_chuyen_sau'],
    shadow: ['thi_phi_khau_thiet', 'hoai_nghi_thai_qua', 'loi_noi_gay_sat_thuong', 'bat_hoa_quan_he'],
  },
  THIEN_TUONG: {
    id: 'THIEN_TUONG',
    name: 'Thiên Tướng',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'THUY',
    yinYang: 'DUONG',
    themes: ['an_tinh', 'trung_thanh', 'phu_ta', 'chinh_khi', 'nghia_hiep'],
    dynamics: ['thuc_thi_menh_lenh', 'ho_tro_lanh_dao', 'dung_duong_cong_ly'],
    constructive: ['tinh_than_trach_nhiem', 'chuyen_nghiep_chuan_muc', 'giup_do_ke_yeu', 'uy_tin_nghe_nghiep'],
    shadow: ['thieu_lap_truong_rieng', 'de_bi_loi_dung', 'bao_thu_khuon_mau', 'thieu_tinh_dot_pha'],
  },
  THIEN_LUONG: {
    id: 'THIEN_LUONG',
    name: 'Thiên Lương',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'MOC',
    yinYang: 'DUONG',
    themes: ['am_tinh', 'tho_tinh', 'dao_duc', 'truyen_thong', 'che_cho'],
    dynamics: ['giao_duc_dan_dat', 'hoa_giai_hung_hoa', 'giu_gin_gia_tri_co'],
    constructive: ['cot_cach_quan_tu', 'y_duc_thay_thuoc', 'tri_tue_tien_boi', 'an_nhien_tu_tai'],
    shadow: ['giao_dieu_kho_khan', 'thich_len_lop_day_doi', 'an_phan_thieu_chi_tien_thu', 'ngai_xung_dot'],
  },
  THAT_SAT: {
    id: 'THAT_SAT',
    name: 'Thất Sát',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'KIM',
    yinYang: 'DUONG',
    themes: ['tien_phong', 'dot_pha', 'quyet_doan', 'dung_khi', 'doc_lap'],
    dynamics: ['tien_cong_khong_lui', 'pha_vo_be_tac', 'giai_quyet_nhanh_gon'],
    constructive: ['ban_linh_kien_cuong', 'danh_nhanh_thang_nhanh', 'dam_duong_dau_song_gio', 'khi_phach_tu_lap'],
    shadow: ['hung_bao_hieu_thang', 'thieu_kien_nhan_hau_can', 'co_doc_xa_lanh', 'ton_hao_than_tam'],
  },
  PHA_QUAN: {
    id: 'PHA_QUAN',
    name: 'Phá Quân',
    discipline: 'TUVI',
    category: 'CHINH_TINH',
    element: 'THUY',
    yinYang: 'AM',
    themes: ['tien_phong_doi_moi', 'pha_cu_lap_moi', 'bien_dong', 'sang_tao_tai_sinh'],
    dynamics: ['dap_do_khuon_mau', 'tai_thiet_tu_hoang_tan', 'tien_phong_mao_hiem'],
    constructive: ['nang_luc_cai_to', 'tien_phong_khai_pha', 'khong_ngai_nghich_canh', 'tao_ra_thoi_the_moi'],
    shadow: ['pha_hoai_nguon_luc', 'bien_dong_that_thuong', 'khac_nghiet_quan_he', 'hao_tan_tai_chinh'],
  },

  // TỨ HÓA (4 TRANSFORMATIONS)
  HOA_LOC: {
    id: 'HOA_LOC',
    name: 'Hóa Lộc',
    discipline: 'TUVI',
    category: 'TU_HOA',
    element: 'MOC',
    yinYang: 'AM',
    themes: ['co_hoi', 'khoi_nguon_tai_loc', 'duyen_phan', 'phat_trien', 'lac_quan'],
    dynamics: ['kich_hoat_tiem_nang', 'mo_rong_nguon_luc', 'tang_truong_thuan_loi'],
    constructive: ['nhay_ben_co_hoi', 'tai_chinh_khoi_sac', 'quan_he_nong_am', 'hoa_khi_sinh_tai'],
    shadow: ['long_tham_khong_day', 'tieu_xai_phung_phi', 'chu_quan_thieu_phong_thu'],
  },
  HOA_QUYEN: {
    id: 'HOA_QUYEN',
    name: 'Hóa Quyền',
    discipline: 'TUVI',
    category: 'TU_HOA',
    element: 'HOA',
    yinYang: 'DUONG',
    themes: ['quyen_luc', 'chi_phoi', 'thuc_thi', 'nang_luc_chuyen_mon', 'tranh_dau'],
    dynamics: ['nam_bat_quyen_kiem_soat', 'khang_dinh_vi_the', 'quyet_liet_dat_muc_tieu'],
    constructive: ['nang_luc_chi_huy', 'tinh_than_trach_nhiem_cao', 'thuc_luc_chuyen_mon', 'thanh_tuu_lon'],
    shadow: ['doc_tai_chuyen_quyen', 'cang_thang_ap_luc', 'tranh_chap_quyen_loi', 'kho_hoa_dong'],
  },
  HOA_KHOA: {
    id: 'HOA_KHOA',
    name: 'Hóa Khoa',
    discipline: 'TUVI',
    category: 'TU_HOA',
    element: 'THUY',
    yinYang: 'DUONG',
    themes: ['danh_tieng', 'tri_thuc', 'giai_nguy', 'chuan_muc', 'bang_cap'],
    dynamics: ['hoa_giai_hung_hoa', 'nang_cao_danh_tieng', 'chuan_hoa_quy_trinh'],
    constructive: ['hoc_van_uyen_tham', 'hoa_hung_thanh_cat', 'uy_tin_xa_hoi', 'diem_dam_minh_triet'],
    shadow: ['hao_danh_hinh_thuc', 'ngai_va_cham_thuc_te', 'tu_man_bang_cap'],
  },
  HOA_KY: {
    id: 'HOA_KY',
    name: 'Hóa Kỵ',
    discipline: 'TUVI',
    category: 'TU_HOA',
    element: 'THUY',
    yinYang: 'AM',
    themes: ['tro_ngai', 'chuyen_hoa_nghiep_qua', 'am_anh', 'thi_phi', 'chieu_sau_noi_tam'],
    dynamics: ['buoc_phai_dao_sau', 'kiem_tra_do_ben', 'thuc_tinh_sau_vap_nga'],
    constructive: ['nghien_cuu_chuyen_sau_phi_thuong', 'canh_giac_cao_do', 'kien_nhan_truoc_nghich_canh', 'noi_luc_tich_luy'],
    shadow: ['thi_phi_hieu_lam', 'bat_an_noi_tam', 'am_anh_that_bai', 'ranh_gioi_kho_thong'],
  },
};

export const TUVI_PALACE_PROFILES: Record<string, TuViPalaceSemanticProfile> = {
  MENH: {
    id: 'MENH',
    name: 'Cung Mệnh',
    discipline: 'TUVI',
    category: 'TAM_PHUONG_TU_CHINH',
    coreFocus: 'Bản thể cốt lõi, tư chất bẩm sinh, thế giới quan và nền tảng nhân cách',
    themes: ['ban_the', 'nhan_cach', 'khi_chat', 'nang_luc_goc'],
    dynamics: ['dinh_hinh_quy_dao', 'ung_xu_voi_cuoc_song'],
    constructive: ['noi_luc_vung_chai', 'y_thuc_tu_chu', 'dinh_huong_ro_rang'],
    shadow: ['co_chap_chu_quan', 'mau_thuan_noi_tam', 'dinh_kien_tu_than'],
  },
  THAN: {
    id: 'THAN',
    name: 'Cung Thân',
    discipline: 'TUVI',
    category: 'TAM_PHUONG_TU_CHINH',
    coreFocus: 'Hậu vận từ 30 tuổi, hành động thực tế và hướng đi được tôi rèn qua trải nghiệm',
    themes: ['hau_van', 'hanh_dong_thuc_te', 'chuyen_bien_trung_nien'],
    dynamics: ['hien_thuc_hoa_ly_tuong', 'chuyen_doi_tam_thuc'],
    constructive: ['truong_thanh_ban_linh', 'hieu_qua_thuc_te', 'an_dinh_su_nghiep'],
    shadow: ['lech_huong_thanh_xuan', 'ap_luc_trach_nhiem', 'hoi_tiec_qua_khu'],
  },
  QUAN_LOC: {
    id: 'QUAN_LOC',
    name: 'Cung Quan Lộc',
    discipline: 'TUVI',
    category: 'TAM_PHUONG_TU_CHINH',
    coreFocus: 'Sự nghiệp, vai trò xã hội, vị thế chuyên môn và phương thức thực thi công việc',
    themes: ['su_nghiep', 'chuyen_mon', 'vi_the_xa_hoi', 'phuong_thuc_lam_viec'],
    dynamics: ['xay_dung_cong_danh', 'thuc_thi_nhiem_vu', 'thang_tien_chuc_vu'],
    constructive: ['chuyen_nghiep_vung_vang', 'uy_tin_lanh_dao', 'thanh_tuu_ben_vung'],
    shadow: ['tham_vong_thai_qua', 'ap_luc_cong_danh', 'xung_dot_dong_nghiep'],
  },
  TAI_BACH: {
    id: 'TAI_BACH',
    name: 'Cung Tài Bạch',
    discipline: 'TUVI',
    category: 'TAM_PHUONG_TU_CHINH',
    coreFocus: 'Dòng tiền, phương thức tạo ra và quản trị của cải, tư duy tài chính',
    themes: ['tai_chinh', 'dong_tien', 'tich_luy', 'phuong_thuc_kiem_tien'],
    dynamics: ['luan_chuyen_nguon_von', 'quan_tri_tai_san', 'thu_hut_tai_loc'],
    constructive: ['kinh_te_an_toan', 'dau_tu_bai_ban', 'nhay_ben_thuong_truong'],
    shadow: ['hao_ton_tai_chinh', 'rui_ro_dau_co', 'ap_luc_no_nan'],
  },
  THIEN_DI: {
    id: 'THIEN_DI',
    name: 'Cung Thiên Di',
    discipline: 'TUVI',
    category: 'TAM_PHUONG_TU_CHINH',
    coreFocus: 'Môi trường xã hội bên ngoài, sự di chuyển, xuất ngoại và giao tế đối ngoại',
    themes: ['ngoai_canh', 'xuat_ngoai', 'doi_ngoai', 'moi_truong_xa_hoi'],
    dynamics: ['tuong_tac_voi_the_gioi', 'nam_bat_co_hoi_phuong_xa', 'thich_ung_van_hoa'],
    constructive: ['quy_nhan_phuong_xa_nang_do', 'mo_rong_tam_nhin', 'thich_ung_nhanh'],
    shadow: ['song_gio_ben_ngoai', 'tai_nan_xe_co', 'co_lap_xa_que'],
  },
  PHU_THE: {
    id: 'PHU_THE',
    name: 'Cung Phu Thê',
    discipline: 'TUVI',
    category: 'LUC_THAN',
    coreFocus: 'Quan hệ hôn nhân, tính cách và phẩm chất người bạn đời, mức độ hòa hợp tình cảm',
    themes: ['hon_nhan', 'ban_doi', 'tinh_cam', 'chia_se_trach_nhiem'],
    dynamics: ['tuong_tac_vo_chong', 'xay_dap_to_am', 'dong_hanh_su_nghiep'],
    constructive: ['hoa_hop_yeu_thuong', 'ban_doi_nang_do', 'gia_dao_em_am'],
    shadow: ['bat_dong_quan_diem', 'khau_thiet_hon_nhan', 'nguy_co_ran_nut'],
  },
  PHUC_DUC: {
    id: 'PHUC_DUC',
    name: 'Cung Phúc Đức',
    discipline: 'TUVI',
    category: 'TAM_PHUONG_TU_CHINH',
    coreFocus: 'Phúc ấm tổ tiên, đời sống tinh thần, sự an lạc nội tâm và họ hàng',
    themes: ['phuc_duc', 'tinh_than', 'dong_toc', 'an_lac_noi_tam'],
    dynamics: ['nuoi_duong_phuc_am', 'giai_nguy_hoan_nan', 'thanh_than_tam_hon'],
    constructive: ['tinh_than_an_nhien', 'phuc_duc_che_cho', 'dong_ho_doan_ket'],
    shadow: ['lo_au_trien_mien', 'phuc_mong_kho_tho', 'bat_hoa_dong_toc'],
  },
  DIEN_TRACH: {
    id: 'DIEN_TRACH',
    name: 'Cung Điền Trạch',
    discipline: 'TUVI',
    category: 'TAI_SAN_THE_XAC',
    coreFocus: 'Bất động sản, cơ nghiệp nhà đất, môi trường nơi cư trú và tài sản tích lũy',
    themes: ['nha_dat', 'bat_dong_san', 'co_nghiep', 'noi_o'],
    dynamics: ['an_cu_lac_nghiep', 'tich_luy_dien_san', 'giu_gin_to_nghiep'],
    constructive: ['dien_san_sung_tuc', 'noi_o_thuan_hoa', 'tich_luy_vung_vang'],
    shadow: ['tranh_chap_nha_dat', 'kho_giu_dat_dai', 'noi_o_bat_on'],
  },
  TAT_ACH: {
    id: 'TAT_ACH',
    name: 'Cung Tật Ách',
    discipline: 'TUVI',
    category: 'TAI_SAN_THE_XAC',
    coreFocus: 'Sức khỏe, thể tạng bẩm sinh, nguy cơ bệnh tật và tai ương tiềm ẩn',
    themes: ['suc_khoe', 'the_chat', 'benh_tat', 'tai_uong'],
    dynamics: ['phong_ngua_benh_tat', 'chuyen_hoa_nghiep_the', 'tang_cuong_the_luc'],
    constructive: ['the_luc_deo_dai', 'gap_thay_gap_thuoc', 'tai_qua_nan_khoi'],
    shadow: ['benh_man_tinh', 'tai_nan_bat_ngo', 'the_luc_suy_yeu'],
  },
  PHU_MAU: {
    id: 'PHU_MAU',
    name: 'Cung Phụ Mẫu',
    discipline: 'TUVI',
    category: 'LUC_THAN',
    coreFocus: 'Mối quan hệ với cha mẹ, sự thừa kế phúc ấm và giáo dưỡng từ gia đình',
    themes: ['cha_me', 'giao_duong', 'thua_ke', 'hieu_thuan'],
    dynamics: ['nhan_su_nang_do', 'hoc_hoi_truyen_thong', 'den_dap_cong_on'],
    constructive: ['cha_me_yeu_thuong', 'gia_giao_vung_chac', 'thua_huong_phuc_am'],
    shadow: ['khac_khau_cha_me', 'thieu_su_gan_ket', 'ap_luc_tu_gia_dinh'],
  },
  HUYNH_DE: {
    id: 'HUYNH_DE',
    name: 'Cung Huynh Đệ',
    discipline: 'TUVI',
    category: 'LUC_THAN',
    coreFocus: 'Quan hệ anh chị em ruột, sự tương trợ trong gia đình và đối tác thân tín',
    themes: ['anh_em', 'tuong_tro', 'chia_se', 'doi_tac_than'],
    dynamics: ['hop_tac_gia_dinh', 'giup_do_lan_nhau', 'chia_se_trach_nhiem'],
    constructive: ['anh_em_hoa_thuan', 'ho_tro_dac_luc', 'tin_cay_lan_nhau'],
    shadow: ['tranh_chap_tai_san', 'xa_cach_dia_ly', 'bat_dong_quan_diem'],
  },
  TU_TUC: {
    id: 'TU_TUC',
    name: 'Cung Tử Tức',
    discipline: 'TUVI',
    category: 'LUC_THAN',
    coreFocus: 'Con cái, thế hệ kế cận, hậu duệ và học trò tiếp nối sự nghiệp',
    themes: ['con_cai', 'hau_due', 'giao_duc_the_he', 'ke_thua'],
    dynamics: ['nuoi_day_the_he_tre', 'truyen_thua_tri_thuc', 'xem_trong_tuong_lai'],
    constructive: ['con_cai_thao_hien', 'the_he_sau_thanh_dat', 'phuc_loc_truong_ton'],
    shadow: ['kho_nuoi_day', 'xa_cach_con_cai', 'lo_lang_the_he_sau'],
  },
  NO_BOC: {
    id: 'NO_BOC',
    name: 'Cung Nô Bộc',
    discipline: 'TUVI',
    category: 'LUC_THAN',
    coreFocus: 'Bạn bè, đồng nghiệp cấp dưới, đối tác hợp tác và nhân sự hỗ trợ',
    themes: ['ban_be', 'cap_duoi', 'nhan_su', 'doi_tac_xa_hoi'],
    dynamics: ['dung_nguoi', 'xay_dung_doi_ngu', 'quan_he_xa_hoi'],
    constructive: ['dong_doi_dac_luc', 'ban_tot_tuong_tro', 'nhan_tam_quy_phuc'],
    shadow: ['bi_phan_boi', 'cap_duoi_lam_phan', 'ton_hao_vi_ban'],
  },
};
