/**
 * MYSTICOS — Semantic Profiles for Western Astrology (Planets, Signs & Houses)
 * Pure Semantic Data (Themes, Dynamics, Constructive, Shadow).
 * NO canned prose paragraphs. 100% Deterministic Knowledge Base.
 */

import { SemanticProfile } from '@mystic/core';

export interface PlanetSemanticProfile extends SemanticProfile {
  category: 'LUMINARY' | 'PERSONAL' | 'SOCIAL' | 'TRANSPERSONAL';
  element: 'FIRE' | 'WATER' | 'AIR' | 'EARTH' | 'ETHER';
  rulingSigns: string[];
}

export interface ZodiacSignSemanticProfile extends SemanticProfile {
  element: 'FIRE' | 'EARTH' | 'AIR' | 'WATER';
  modality: 'CARDINAL' | 'FIXED' | 'MUTABLE';
  polarity: 'YANG' | 'YIN';
  ruler: string;
}

export interface HouseSemanticProfile extends SemanticProfile {
  houseNumber: number;
  domain: string;
  hemisphere: 'EAST' | 'WEST' | 'NORTH' | 'SOUTH';
}

export const ASTROLOGY_PLANET_PROFILES: Record<string, PlanetSemanticProfile> = {
  sun: {
    id: 'sun',
    name: 'Mặt Trời (Sun)',
    discipline: 'ASTROLOGY',
    category: 'LUMINARY',
    element: 'FIRE',
    rulingSigns: ['LEO'],
    themes: ['y_chi_song', 'ban_nga', 'sang_tao', 'su_song', 'danh_tieng'],
    dynamics: ['toa_sang_chu_dong', 'hien_thuc_hoa_muc_tieu', 'khang_dinh_ban_than'],
    constructive: ['hao_sang', 'chinh_truc', 'tam_nhin_lanh_dao', 'long_can_dam'],
    shadow: ['tu_phu_kieu_ngao', 'doc_doan', 'nong_nay', 'hao_nhoang_hinh_thuc'],
  },
  moon: {
    id: 'moon',
    name: 'Mặt Trăng (Moon)',
    discipline: 'ASTROLOGY',
    category: 'LUMINARY',
    element: 'WATER',
    rulingSigns: ['CANCER'],
    themes: ['cam_xuc', 'truc_giac', 'an_toan_noi_tam', 'tiem_thuc', 'nuoi_duong'],
    dynamics: ['phan_xa_ban_nang', 'chuyen_hoa_tam_trang', 'tim_kiem_su_che_cho'],
    constructive: ['thau_cam_sau_sac', 'truc_giac_nhay_ben', 'an_ui_chua_lanh', 'trung_thanh_tinh_cam'],
    shadow: ['da_sau_da_cam', 'tam_ly_bat_an', 'dong_trang_thai_u_nghen', 'phu_thuoc_cam_xuc'],
  },
  mercury: {
    id: 'mercury',
    name: 'Thủy Tinh (Mercury)',
    discipline: 'ASTROLOGY',
    category: 'PERSONAL',
    element: 'AIR',
    rulingSigns: ['GEMINI', 'VIRGO'],
    themes: ['tu_duy', 'giao_tiep', 'phan_tich', 'thong_tin', 'thich_ung'],
    dynamics: ['xu_ly_du_lieu_nhanh', 'truyen_tai_y_niem', 'ket_noi_mang_luoi'],
    constructive: ['sac_sao_nhanh_nhay', 'tu_duy_logic_chuan_xac', 'hoc_hoi_khong_ngung', 'giao_thiep_thong_minh'],
    shadow: ['phan_tan_suy_nghi', 'hoai_nghi_loi_cu', 'noi_nhieu_lam_it', 'than_kinh_cang_thang'],
  },
  venus: {
    id: 'venus',
    name: 'Kim Tinh (Venus)',
    discipline: 'ASTROLOGY',
    category: 'PERSONAL',
    element: 'EARTH',
    rulingSigns: ['TAURUS', 'LIBRA'],
    themes: ['tinh_yeu', 'gia_tri', 'tham_my', 'hoa_hop', 'tai_chinh'],
    dynamics: ['thu_hut_ket_noi', 'can_bang_cac_thoi_cuc', 'dinh_gia_chat_luong'],
    constructive: ['duyen_dang_hoa_nha', 'gu_tham_my_tinh_te', 'xay_dung_quan_he_vung_chac', 'an_dinh_tai_san'],
    shadow: ['thoa_hiep_gia_tao', 'luoi_bieng_huong_thu', 'thien_ve_hinh_thuc', 'ngai_xung_dot'],
  },
  mars: {
    id: 'mars',
    name: 'Hỏa Tinh (Mars)',
    discipline: 'ASTROLOGY',
    category: 'PERSONAL',
    element: 'FIRE',
    rulingSigns: ['ARIES', 'SCORPIO'],
    themes: ['hanh_dong', 'khi_phach', 'dam_me', 'canh_tranh', 'ranh_gioi'],
    dynamics: ['tien_cong_truc_dien', 'pha_vo_rao_can', 'bao_ve_chu_quyen'],
    constructive: ['dung_khi_tien_phong', 'quyet_doan_dut_khoat', 'the_luc_sung_man', 'dam_chiu_trach_nhiem'],
    shadow: ['hung_hang_nong_nay', 'gay_han_xung_dot', 'thieu_kien_nhan', 'hanh_dong_boc_dong'],
  },
  jupiter: {
    id: 'jupiter',
    name: 'Mộc Tinh (Jupiter)',
    discipline: 'ASTROLOGY',
    category: 'SOCIAL',
    element: 'FIRE',
    rulingSigns: ['SAGITTARIUS', 'PISCES'],
    themes: ['mo_rong', 'niem_tin', 'triet_ly', 'may_man', 'tri_thuc_bac_cao'],
    dynamics: ['nang_tam_nhan_thuc', 'mo_rong_co_hoi', 'lan_toa_lac_quan'],
    constructive: ['tam_nhin_vi_mo', 'khoan_dung_quang_dai', 'tinh_than_cau_tien', 'phuc_khi_nang_do'],
    shadow: ['chu_quan_thai_qua', 'loi_hua_kho_thuc_hien', 'phung_phi_nguon_luc', 'tu_man'],
  },
  saturn: {
    id: 'saturn',
    name: 'Thổ Tinh (Saturn)',
    discipline: 'ASTROLOGY',
    category: 'SOCIAL',
    element: 'EARTH',
    rulingSigns: ['CAPRICORN', 'AQUARIUS'],
    themes: ['cau_truc', 'ky_luat', 'thoi_gian', 'trach_nhiem', 'gioi_han'],
    dynamics: ['kiem_soat_ap_luc', 'xay_dung_be_mong', 'thu_thach_do_ben'],
    constructive: ['kien_dinh_sat_da', 'chuyen_nghiep_chuan_muc', 'thanh_tuu_truong_cuu', 'kham_kho_vuot_kho'],
    shadow: ['cung_nhac_bao_thu', 'bi_quan_lo_au', 'khat_khe_lanh_lung', 'tri_hoan_do_so_hai'],
  },
  uranus: {
    id: 'uranus',
    name: 'Thiên Vương Tinh (Uranus)',
    discipline: 'ASTROLOGY',
    category: 'TRANSPERSONAL',
    element: 'AIR',
    rulingSigns: ['AQUARIUS'],
    themes: ['dot_pha', 'doi_moi', 'tu_do', 'khac_biet', 'bat_ngo'],
    dynamics: ['pha_vo_khuon_mau', 'thuc_tinh_nhan_thuc', 'khai_sang_tu_tuong'],
    constructive: ['sang_tao_cach_mang', 'doc_lap_tu_chu', 'tam_nhin_di_truoc_thoi_dai', 'nhan_dao_tien_bo'],
    shadow: ['lap_di_that_thuong', 'phan_nghich_mu_quang', 'gay_roi_bat_on', 'mat_ket_noi_thuc_te'],
  },
  neptune: {
    id: 'neptune',
    name: 'Hải Vương Tinh (Neptune)',
    discipline: 'ASTROLOGY',
    category: 'TRANSPERSONAL',
    element: 'WATER',
    rulingSigns: ['PISCES'],
    themes: ['tam_linh', 'nghe_thuat', 'tu_bi', 'hoa_nhap', 'ao_anh'],
    dynamics: ['xoa_nhoa_ranh_gioi', 'thang_hoa_tinh_than', 'cam_thu_vo_thuc'],
    constructive: ['long_trac_an_vo_dieu_kien', 'tri_tuong_tuong_ky_dieu', 'truc_giac_tam_linh', 'chua_lanh_tam_hon'],
    shadow: ['ao_tuong_xa_roi_thuc_te', 'ne_tranh_trach_nhiem', 'de_bi_lua_doi', 'nghiem_ngap_u_me'],
  },
  pluto: {
    id: 'pluto',
    name: 'Diêm Vương Tinh (Pluto)',
    discipline: 'ASTROLOGY',
    category: 'TRANSPERSONAL',
    element: 'WATER',
    rulingSigns: ['SCORPIO'],
    themes: ['tai_sinh', 'chuyen_hoa_sau_sac', 'quyen_luc_ngam', 'buong_bo', 'chan_ly'],
    dynamics: ['lot_xac_qua_nghich_canh', 'thau_thi_bong_toi', 'tai_thiet_tu_tro_tan'],
    constructive: ['noi_luc_phi_thuong', 'ban_linh_tai_sinh', 'nhin_thau_ban_chat', 'trung_thanh_sat_son'],
    shadow: ['am_anh_kiem_soat', 'nghi_ngo_doc_doan', 'huy_hoai_cuc_doan', 'bao_thu_oan_han'],
  },
};

export const ASTROLOGY_ZODIAC_PROFILES: Record<string, ZodiacSignSemanticProfile> = {
  ARIES: {
    id: 'ARIES',
    name: 'Bạch Dương (Aries)',
    discipline: 'ASTROLOGY',
    element: 'FIRE',
    modality: 'CARDINAL',
    polarity: 'YANG',
    ruler: 'mars',
    themes: ['tien_phong', 'hanh_dong_nhanh', 'can_dam', 'khoi_nguyen'],
    dynamics: ['tien_phong_khai_pha', 'chinh_phuc_muc_tieu'],
    constructive: ['nhiet_huyet_tiem_tang', 'quyet_doan', 'trung_thuc_thang_than'],
    shadow: ['nong_voi', 'thieu_kien_nhan', 'hieu_thang'],
  },
  TAURUS: {
    id: 'TAURUS',
    name: 'Kim Ngưu (Taurus)',
    discipline: 'ASTROLOGY',
    element: 'EARTH',
    modality: 'FIXED',
    polarity: 'YIN',
    ruler: 'venus',
    themes: ['ben_bi', 'thuc_tien', 'an_toan_vat_chat', 'on_dinh'],
    dynamics: ['tich_luy_vung_chac', 'bao_ton_nguon_luc'],
    constructive: ['dang_tin_cay', 'kien_tri_tuyet_doi', 'quan_tri_tai_san'],
    shadow: ['bao_thu', 'ngai_thay_doi', 'qua_chu_trong_vat_chat'],
  },
  GEMINI: {
    id: 'GEMINI',
    name: 'Song Tử (Gemini)',
    discipline: 'ASTROLOGY',
    element: 'AIR',
    modality: 'MUTABLE',
    polarity: 'YANG',
    ruler: 'mercury',
    themes: ['linh_hoat', 'thong_tin', 'giao_tiep', 'da_chieu'],
    dynamics: ['ket_noi_y_tuong', 'thich_ung_nhanh'],
    constructive: ['thong_minh_nhanh_nhen', 'hoc_hoi_nhanh', 'giao_thiep_rong'],
    shadow: ['phan_tan', 'thieu_chuyen_sau', 'de_thay_doi_cam_hung'],
  },
  CANCER: {
    id: 'CANCER',
    name: 'Cự Giải (Cancer)',
    discipline: 'ASTROLOGY',
    element: 'WATER',
    modality: 'CARDINAL',
    polarity: 'YIN',
    ruler: 'moon',
    themes: ['nuoi_duong', 'cam_xuc', 'gia_dinh', 'truc_giac'],
    dynamics: ['bao_ve_to_am', 'thau_cam_sau_sac'],
    constructive: ['chu_dao', 'an_can_yeu_thuong', 'truc_giac_manh'],
    shadow: ['phong_thu_thai_qua', 'tam_trang_that_thuong', 'lo_xa'],
  },
  LEO: {
    id: 'LEO',
    name: 'Sư Tử (Leo)',
    discipline: 'ASTROLOGY',
    element: 'FIRE',
    modality: 'FIXED',
    polarity: 'YANG',
    ruler: 'sun',
    themes: ['toa_sang', 'tu_ton', 'sang_tao', 'lanh_dao'],
    dynamics: ['truyen_cam_hung', 'khang_dinh_vi_the'],
    constructive: ['hao_sang', 'tu_tin', 'trung_thanh', 'sang_tao'],
    shadow: ['kieu_ngao', 'can_duoc_tan_duong', 'doc_doan'],
  },
  VIRGO: {
    id: 'VIRGO',
    name: 'Xử Nữ (Virgo)',
    discipline: 'ASTROLOGY',
    element: 'EARTH',
    modality: 'MUTABLE',
    polarity: 'YIN',
    ruler: 'mercury',
    themes: ['phan_tich', 'hoan_thien', 'phung_su', 'ky_luat'],
    dynamics: ['toi_uu_quy_trinh', 'giai_quyet_chi_tiet'],
    constructive: ['can_than', 'ti_mi', 'chuyen_nghiep', 'thuc_te'],
    shadow: ['cau_toan_thai_qua', 'hay_chi_trich', 'tu_gay_ap_luc'],
  },
  LIBRA: {
    id: 'LIBRA',
    name: 'Thiên Bình (Libra)',
    discipline: 'ASTROLOGY',
    element: 'AIR',
    modality: 'CARDINAL',
    polarity: 'YANG',
    ruler: 'venus',
    themes: ['can_bang', 'cong_ly', 'hoa_hop', 'hop_tac'],
    dynamics: ['dung_hoa_xung_dot', 'tao_dung_lien_ket'],
    constructive: ['ngoai_giao_kheo_leo', 'tham_my_cao', 'cong_bang'],
    shadow: ['do_du_kho_quyet', 'tranh_ne_xung_dot', 'phu_thuoc_nguoi_khac'],
  },
  SCORPIO: {
    id: 'SCORPIO',
    name: 'Bọ Cạp (Scorpio)',
    discipline: 'ASTROLOGY',
    element: 'WATER',
    modality: 'FIXED',
    polarity: 'YIN',
    ruler: 'pluto',
    themes: ['thau_thi', 'chuyen_hoa', 'sau_sac', 'kien_dinh'],
    dynamics: ['dao_sau_ban_chat', 'tai_sinh_tu_nghich_canh'],
    constructive: ['ban_linh_phi_thuong', 'trung_thanh_tuyet_doi', 'truc_giac_thau_suot'],
    shadow: ['da_nghi', 'kiem_soat_ngam', 'kho_buong_bo'],
  },
  SAGITTARIUS: {
    id: 'SAGITTARIUS',
    name: 'Nhân Mã (Sagittarius)',
    discipline: 'ASTROLOGY',
    element: 'FIRE',
    modality: 'MUTABLE',
    polarity: 'YANG',
    ruler: 'jupiter',
    themes: ['tu_do', 'kham_pha', 'triet_ly', 'lac_quan'],
    dynamics: ['mo_rong_chan_troi', 'truyen_ba_ly_tuong'],
    constructive: ['phong_khoang', 'chan_thuc', 'tam_nhin_xa'],
    shadow: ['thieu_can_trong', 'loi_hua_qua_tam', 'ngai_cam_ket'],
  },
  CAPRICORN: {
    id: 'CAPRICORN',
    name: 'Ma Kết (Capricorn)',
    discipline: 'ASTROLOGY',
    element: 'EARTH',
    modality: 'CARDINAL',
    polarity: 'YIN',
    ruler: 'saturn',
    themes: ['ky_luat', 'trach_nhiem', 'thanh_tuu_dai_han', 'cau_truc'],
    dynamics: ['xay_dung_su_nghiep', 'leo_len_dinh_cao'],
    constructive: ['kien_dinh', 'chuyen_nghiep', 'quy_cu_vung_chac'],
    shadow: ['lanh_lung_khac_nghiet', 'qua_tham_cong_tiec_viec', 'bi_quan'],
  },
  AQUARIUS: {
    id: 'AQUARIUS',
    name: 'Bảo Bình (Aquarius)',
    discipline: 'ASTROLOGY',
    element: 'AIR',
    modality: 'FIXED',
    polarity: 'YANG',
    ruler: 'uranus',
    themes: ['doi_moi', 'doc_lap', 'nhan_dao', 'tri_thuc_tien_tien'],
    dynamics: ['thuc_day_tien_bo', 'pha_vo_khuon_sao'],
    constructive: ['sang_tao_dac_biet', 'cong_bang_binh_dang', 'tam_nhin_tuong_lai'],
    shadow: ['xa_cach_cam_xuc', 'cung_dau_co_chap', 'lap_di'],
  },
  PISCES: {
    id: 'PISCES',
    name: 'Song Ngư (Pisces)',
    discipline: 'ASTROLOGY',
    element: 'WATER',
    modality: 'MUTABLE',
    polarity: 'YIN',
    ruler: 'neptune',
    themes: ['thau_cam', 'nghe_thuat', 'tam_linh', 'hoa_nhap'],
    dynamics: ['chua_lanh_tinh_than', 'ket_noi_vo_hinh'],
    constructive: ['giau_long_trac_an', 'truc_giac_thien_bam', 'sang_tao_nghe_thuat'],
    shadow: ['mo_ho_thieu_thuc_te', 'de_bi_loi_dung', 'ne_tranh_thuc_tai'],
  },
};

export const ASTROLOGY_HOUSE_PROFILES: Record<string, HouseSemanticProfile> = {
  house_1: {
    id: 'house_1',
    name: 'Nhà 1 (Cung Mọc / Ascendant)',
    discipline: 'ASTROLOGY',
    houseNumber: 1,
    domain: 'Ban Than & Dinh Dang',
    hemisphere: 'EAST',
    themes: ['ban_nga_ngoai_hien', 'the_chat', 'khoi_dau', 'phong_thai'],
    dynamics: ['khang_dinh_su_hien_dien', 'tao_an_tuong_dau_tien'],
    constructive: ['tu_tin', 'chu_dong', 'ngoai_hinh_sang'],
    shadow: ['tu_trung_tam', 'qua_quan_tam_ve_ngoai'],
  },
  house_2: {
    id: 'house_2',
    name: 'Nhà 2 (Tài Sản & Giá Trị Bản Thân)',
    discipline: 'ASTROLOGY',
    houseNumber: 2,
    domain: 'Tai Chinh & Gia Tri',
    hemisphere: 'NORTH',
    themes: ['tai_chinh', 'thu_nhap', 'gia_tri_tu_than', 'an_toan_vat_chat'],
    dynamics: ['kiem_tien', 'tich_luy', 'xac_lap_gia_tri'],
    constructive: ['kinh_te_on_dinh', 'quan_tri_nguon_luc', 'tu_trong'],
    shadow: ['bam_chap_vat_chat', 'bat_an_tai_chinh'],
  },
  house_3: {
    id: 'house_3',
    name: 'Nhà 3 (Giao Tiếp & Học Tập Cơ Bản)',
    discipline: 'ASTROLOGY',
    houseNumber: 3,
    domain: 'Giao Tiep & Moi Truong Gan',
    hemisphere: 'NORTH',
    themes: ['ngon_ngu', 'giao_tiep', 'hoc_tap', 'anh_em', 'di_lai_gan'],
    dynamics: ['trao_doi_thong_tin', 'ket_noi_hang_xom'],
    constructive: ['tu_duy_linh_hoat', 'dien_dat_luu_loat', 'ham_hoc'],
    shadow: ['noi_nham', 'nong_can', 'phan_tan_suy_nghi'],
  },
  house_4: {
    id: 'house_4',
    name: 'Nhà 4 (Gia Đình & Cội Nguồn)',
    discipline: 'ASTROLOGY',
    houseNumber: 4,
    domain: 'To Am & Noi Tam',
    hemisphere: 'NORTH',
    themes: ['to_am', 'nguon_coi', 'cha_me', 'an_toan_cam_xuc'],
    dynamics: ['xay_dung_nen_mong', 'nuoi_duong_noi_tam'],
    constructive: ['gia_dao_vung_chac', 'tam_hon_binh_an', 'hieu_thuan'],
    shadow: ['dong_kinh_nghiem_qua_khu', 'phu_thuoc_gia_dinh'],
  },
  house_5: {
    id: 'house_5',
    name: 'Nhà 5 (Sáng Tạo, Con Cái & Niềm Vui)',
    discipline: 'ASTROLOGY',
    houseNumber: 5,
    domain: 'Sang Tao & Huong Thu',
    hemisphere: 'NORTH',
    themes: ['sang_tao_nghe_thuat', 'tinh_yeu_lang_man', 'con_cai', 'giai_tri'],
    dynamics: ['boc_lo_ca_tinh', 'tan_huong_cuoc_song'],
    constructive: ['say_me_sang_tao', 'trai_tim_nong_am', 'giao_duc_con_tot'],
    shadow: ['sa_da_vui_choi', 'dau_co_mao_hiem', 'tu_man'],
  },
  house_6: {
    id: 'house_6',
    name: 'Nhà 6 (Công Việc Hằng Ngày & Sức Khỏe)',
    discipline: 'ASTROLOGY',
    houseNumber: 6,
    domain: 'Phung Su & The Chat',
    hemisphere: 'NORTH',
    themes: ['thoi_quen_hang_ngay', 'suc_khoe', 'phung_su', 'ky_nang_chuyen_mon'],
    dynamics: ['lam_viec_can_man', 'ren_luyen_the_chat'],
    constructive: ['ky_luat', 'chuyen_nghiep', 'cham_soc_suc_khoe'],
    shadow: ['lam_viec_qua_tai', 'lo_lang_benh_tat', 'hay_soi_moi'],
  },
  house_7: {
    id: 'house_7',
    name: 'Nhà 7 (Đối Tác & Hôn Nhân / Descendant)',
    discipline: 'ASTROLOGY',
    houseNumber: 7,
    domain: 'Hon Nhan & Hop Tac',
    hemisphere: 'WEST',
    themes: ['ban_doi', 'hon_nhan', 'doi_tac_kinh_doanh', 'cam_ket_phap_ly'],
    dynamics: ['doi_thoai_hai_chieu', 'can_bang_quyen_loi'],
    constructive: ['hoa_hop_hon_nhan', 'hop_tac_ben_vung', 'cong_bang'],
    shadow: ['danh_mat_ban_than', 'mau_thuan_ran_nut', 'phu_thuoc'],
  },
  house_8: {
    id: 'house_8',
    name: 'Nhà 8 (Tài Sản Chung, Chuyển Hóa & Tâm Lý Sâu)',
    discipline: 'ASTROLOGY',
    houseNumber: 8,
    domain: 'Tai San Chung & Tai Sinh',
    hemisphere: 'SOUTH',
    themes: ['nguon_von_chung', 'thua_ke', 'tai_sinh', 'chieu_sau_tam_ly'],
    dynamics: ['lot_xac_qua_khung_hoang', 'chia_se_tai_chinh'],
    constructive: ['quan_tri_von_gioi', 'ban_linh_tai_sinh', 'thau_thi_tam_ly'],
    shadow: ['tranh_chap_tai_chinh', 'am_anh_kiem_soat', 'so_ton_thuong'],
  },
  house_9: {
    id: 'house_9',
    name: 'Nhà 9 (Triết Học, Học Vấn Cao & Xuất Ngoại)',
    discipline: 'ASTROLOGY',
    houseNumber: 9,
    domain: 'Tam Nhin & Tri Thuc Bac Cao',
    hemisphere: 'SOUTH',
    themes: ['hoc_van_bac_cao', 'xuat_ngoai', 'triet_ly_song', 'tam_nhin_xa'],
    dynamics: ['kham_pha_chan_ly', 'mo_rong_the_gioi_quan'],
    constructive: ['uy_bac', 'phong_khoang', 'hoi_nhap_quoc_te'],
    shadow: ['giao_dieu', 'ly_thuyet_suong', 'xem_thuong_thuc_te'],
  },
  house_10: {
    id: 'house_10',
    name: 'Nhà 10 (Sự Nghiệp, Danh Tiếng / Midheaven MC)',
    discipline: 'ASTROLOGY',
    houseNumber: 10,
    domain: 'Su Nghiep & Vi The Xa Hoi',
    hemisphere: 'SOUTH',
    themes: ['danh_tieng', 'su_nghiep_dinh_cao', 'vi_tri_lanh_dao', 'uy_tin_cong_chung'],
    dynamics: ['xay_dung_di_san', 'thuc_thi_trach_nhiem'],
    constructive: ['thanh_tuu_vuot_troi', 'lanh_dao_co_tam', 'uy_tin_vung_chac'],
    shadow: ['tham_vong_mu_quang', 'ap_luc_danh_tieng', 'bo_be_gia_dinh'],
  },
  house_11: {
    id: 'house_11',
    name: 'Nhà 11 (Cộng Đồng, Lý Tưởng & Bạn Bè)',
    discipline: 'ASTROLOGY',
    houseNumber: 11,
    domain: 'Cong Dong & Uoc Mo',
    hemisphere: 'SOUTH',
    themes: ['ly_tuong_nhan_van', 'mang_luoi_ban_be', 'cong_dong', 'du_an_tuong_lai'],
    dynamics: ['hop_luc_tap_the', 'hien_thuc_hoa_uoc_mo'],
    constructive: ['tinh_than_dong_doi', 'co_anh_huong_xa_hoi', 'tam_nhin_nhan_dao'],
    shadow: ['a_dua_theo_so_dong', 'ly_tuong_viển_vông', 'lanh_nhat_ca_nhan'],
  },
  house_12: {
    id: 'house_12',
    name: 'Nhà 12 (Tiềm Thức, Giải Thoát & Nhân Quả)',
    discipline: 'ASTROLOGY',
    houseNumber: 12,
    domain: 'Tiem Thuc & Sieu Viet',
    hemisphere: 'EAST',
    themes: ['tiem_thuc', 'tinh_tam', 'long_trac_an', 'nhan_qua', 'chua_lanh'],
    dynamics: ['buong_bo_ban_nga', 'ket_noi_sieu_nhien'],
    constructive: ['truc_giac_phi_thuong', 'an_nhien_tu_tai', 'phung_su_vo_vi'],
    shadow: ['ne_tranh_thuc_te', 'tu_huy_hoai_ngam', 'cam_giac_co_doc'],
  },
};
