import { InterpretationRule } from '../types/rule.js';

export const TAROT_RULES: InterpretationRule[] = [
  {
    ruleId: 'RUL_TAROT_FOOL_PRESENT',
    domain: 'tarot',
    school: 'Rider-Waite-Smith',
    sourceIds: ['SRC_TAROT_WAITE_1911'],
    claimIds: ['CLM_TAROT_FOOL_001'],
    preconditions: [
      { field: 'cardCode', operator: 'EQUALS', value: 'MAJOR_0' },
      { field: 'positionIndex', operator: 'EQUALS', value: 0 },
      { field: 'isReversed', operator: 'EQUALS', value: false },
    ],
    semanticInputs: ['state_of_pure_potentiality_and_spiritual_quest'],
    derivedSignals: ['SIG_RADICAL_BEGINNING', 'SIG_INTUITIVE_LEAP'],
    priority: 90,
    evidenceLevel: 'A',
    confidence: 'verified',
    pattern: 'SPONTANEOUS_INITIATIVE',
    notes: 'The Fool tại vị trí Hiện Tại (Upright) biểu thị khởi đầu mới không vướng bận định kiến.',
  },
  {
    ruleId: 'RUL_TAROT_7P_CHALLENGE',
    domain: 'tarot',
    school: 'Rider-Waite-Smith',
    sourceIds: ['SRC_TAROT_WAITE_1911'],
    claimIds: ['CLM_TAROT_7P_001'],
    preconditions: [
      { field: 'cardCode', operator: 'EQUALS', value: 'MINOR_PENTACLES_7' },
      { field: 'positionIndex', operator: 'EQUALS', value: 1 },
    ],
    semanticInputs: ['deliberate_pause_for_evaluating_accumulated_work'],
    derivedSignals: ['SIG_REASSESSMENT_FATIGUE', 'SIG_EVALUATION_IMPEDIMENT'],
    priority: 85,
    evidenceLevel: 'A',
    confidence: 'verified',
    pattern: 'EVALUATION_FRICTION',
    notes: '7 Pentacles tại vị trí Thử Thách đòi hỏi kiểm định lại tính hiệu quả của công sức đã đầu tư.',
  },
  {
    ruleId: 'RUL_TAROT_TOWER_REVERSED',
    domain: 'tarot',
    school: 'Rider-Waite-Smith',
    sourceIds: ['SRC_TAROT_WAITE_1911'],
    claimIds: ['CLM_TAROT_TOWER_001'],
    preconditions: [
      { field: 'cardCode', operator: 'EQUALS', value: 'MAJOR_16' },
      { field: 'isReversed', operator: 'EQUALS', value: true },
    ],
    semanticInputs: ['shatters_false_structures'],
    derivedSignals: ['SIG_RESISTING_COLLAPSE', 'SIG_DELAYED_PURGATION'],
    priority: 88,
    evidenceLevel: 'A',
    confidence: 'verified',
    pattern: 'RESISTING_INEVITABLE_PURGE',
    notes: 'The Tower đảo ngược biểu thị sự níu kéo cấu trúc lỗi thời gây tích tụ căng thẳng ngầm.',
  },
];
