import { InterpretationRule } from '../types/rule.js';

export const TUVI_RULES: InterpretationRule[] = [
  {
    ruleId: 'RUL_TUVI_MENH_TUVI_TINHTRINH',
    domain: 'tuvi',
    school: 'Nam Phái Toàn Thư',
    sourceIds: ['SRC_TUVI_TOAN_THU'],
    claimIds: ['CLM_TUVI_TUVI_MENH_001'],
    preconditions: [
      { field: 'palaceName', operator: 'EQUALS', value: 'Mệnh' },
      { field: 'starCode', operator: 'EQUALS', value: 'TU_VI' },
      { field: 'brightness', operator: 'IN', value: ['M', 'V', 'D'] },
    ],
    semanticInputs: ['leadership_dignity_and_authoritative_rectitude'],
    derivedSignals: ['SIG_EXECUTIVE_COMMAND', 'SIG_SELF_RELIANCE'],
    priority: 100,
    evidenceLevel: 'A',
    confidence: 'verified',
    pattern: 'SOVEREIGN_AUTHORITY',
    notes: 'Tử Vi miếu vượng đắc địa tại Mệnh xác lập tư chất dẫn dắt độc lập và trọng danh dự.',
  },
  {
    ruleId: 'RUL_TUVI_HOALOC_TAIBACK',
    domain: 'tuvi',
    school: 'Nam Phái Toàn Thư',
    sourceIds: ['SRC_TUVI_TOAN_THU'],
    claimIds: ['CLM_TUVI_HOALOC_MENH_001'],
    preconditions: [
      { field: 'palaceName', operator: 'IN', value: ['Mệnh', 'Tài Bạch'] },
      { field: 'starCode', operator: 'EQUALS', value: 'HOA_LOC' },
    ],
    semanticInputs: ['resource_attraction_and_harmonious_enterprise'],
    derivedSignals: ['SIG_RESOURCE_EXPANSION', 'SIG_ENTERPRISE_FACILITATION'],
    priority: 85,
    evidenceLevel: 'A',
    confidence: 'verified',
    pattern: 'PROSPERITY_FLOW',
    notes: 'Hóa Lộc tại Mệnh hoặc Tài gia tăng năng lực chuyển hóa ý tưởng thành giá trị kinh tế.',
  },
  {
    ruleId: 'RUL_TUVI_HOAKY_TAM_TRIET',
    domain: 'tuvi',
    school: 'Trung Châu Môn',
    sourceIds: ['SRC_TUVI_TRUNG_CHAU_VUONG_DINH_CHI'],
    claimIds: ['CLM_TUVI_HOAKY_001'],
    preconditions: [
      { field: 'starCode', operator: 'EQUALS', value: 'HOA_KY' },
      { field: 'palaceName', operator: 'IN', value: ['Mệnh', 'Tật Ách'] },
    ],
    semanticInputs: ['karmic_entanglement_obsessive_worry_and_friction'],
    derivedSignals: ['SIG_OBSESSIVE_SCRUTINY', 'SIG_VULNERABILITY_FOCUS'],
    priority: 95,
    evidenceLevel: 'B',
    confidence: 'supported',
    pattern: 'INTERNAL_KNOT',
    notes: 'Hóa Kỵ kích hoạt điểm tập trung tâm lý phức tạp cần chuyển hóa từ hoài nghi sang thấu hiểu.',
  },
];
