import { SourceConflict } from '../types/conflict.js';

export const REGISTERED_CONFLICTS: SourceConflict[] = [
  {
    conflictId: 'CONF_TAROT_LOVERS_MEANING',
    topic: 'Ý nghĩa lá The Lovers (VI): Tình yêu hợp nhất vs Ngã rẽ đạo đức',
    sources: ['SRC_TAROT_WAITE_1911', 'SRC_TAROT_MATHERS_1888'],
    schoolA: 'Rider-Waite-Smith (A.E. Waite)',
    schoolB: 'Marseille / Cổ Điển',
    claimA: 'Hôn phối thiêng liêng, sự hòa hợp tâm hồn dưới sự chứng giám của thiên thần Raphael.',
    claimB: 'Người thanh niên đứng giữa hai người phụ nữ phân vân lựa chọn giữa đức hạnh và dục vọng.',
    conflictType: 'different_school',
    resolution: 'school_specific',
    notes: 'Mysticos ưu tiên biểu tượng RWS cho bộ bài RWS; không đánh đồng với dị bản Marseille.',
  },
  {
    conflictId: 'CONF_TUVI_CAN_CANH_TU_HOA',
    topic: 'Tứ Hóa Can Canh: Thái Dương Hóa Khoa vs Thiên Phủ Hóa Khoa',
    sources: ['SRC_TUVI_TOAN_THU', 'SRC_TUVI_TRUNG_CHAU_VUONG_DINH_CHI'],
    schoolA: 'Toàn Thư Nam Phái (Nhật Vũ Đồng Âm)',
    schoolB: 'Trung Châu Phái (Nhật Vũ Âm Đồng)',
    claimA: 'Can Canh: Dương Vũ Đồng Âm (Thái Dương Hóa Lộc, Vũ Khúc Hóa Quyền, Thiên Đồng Hóa Khoa, Thái Âm Hóa Kỵ).',
    claimB: 'Can Canh: Nhật Vũ Âm Đồng (Thái Dương Hóa Lộc, Vũ Khúc Hóa Quyền, Thái Âm Hóa Khoa, Thiên Đồng Hóa Kỵ).',
    conflictType: 'different_school',
    resolution: 'keep_separate',
    notes: 'Giữ cấu hình trường phái độc lập theo cài đặt methodVersion của lá số; không tự động dung hòa.',
  },
  {
    conflictId: 'CONF_ASTRO_PLUTO_RULERSHIP',
    topic: 'Chủ quản Bọ Cạp: Sao Hỏa cổ điển vs Diêm Vương Tinh hiện đại',
    sources: ['SRC_ASTRO_PTOLEMY_TETRABIBLOS', 'SRC_ASTRO_HAND_1976'],
    schoolA: 'Classical Hellenistic (Ptolemy)',
    schoolB: 'Modern Psychological Astrology',
    claimA: 'Sao Hỏa (Mars) cai quản toàn diện Bạch Dương và Bọ Cạp.',
    claimB: 'Sao Diêm Vương (Pluto) đồng cai quản Bọ Cạp, sao Hỏa giữ vai trò truyền thống.',
    conflictType: 'different_era',
    resolution: 'prefer_primary',
    notes: 'Lấy vị thế Sao Hỏa làm nền tảng tính toán phẩm tính, Diêm Vương Tinh dùng để bổ trợ luận giải tâm lý.',
  },
  {
    conflictId: 'CONF_NUM_PYTHAGORAS_VS_MODERN',
    topic: 'Ý nghĩa Số 5: Triết lý Hôn phối thiêng liêng vs Tự do phiêu lưu hiện đại',
    sources: ['SRC_NUM_PYTHAGORAS', 'SRC_NUM_GOODWIN'],
    schoolA: 'Greek Classical Arithmology (Theologoumena Arithmeticae)',
    schoolB: 'Modern Western Numerology',
    claimA: 'Số 5 (Pentad) là biểu tượng hôn phối (2 Nữ tính + 3 Nam tính), công lý và trung tâm.',
    claimB: 'Số 5 trong Đường Đời là năng lượng tự do, biến chuyển, phiêu lưu và trải nghiệm giác quan.',
    conflictType: 'different_definition',
    resolution: 'school_specific',
    notes: 'Rạch ròi: Luận giải đời sống cá nhân dùng Modern Numerology; không gán ghép cho triết gia Pythagoras cổ đại.',
  },
];
