import { SourceRecord } from '../types/source.js';

export const ASTROLOGY_SOURCES: SourceRecord[] = [
  {
    sourceId: 'SRC_ASTRO_PTOLEMY_TETRABIBLOS',
    domain: 'astrology',
    title: 'Tetrabiblos (Quadripartitum)',
    author: 'Claudius Ptolemy',
    publisher: 'Loeb Classical Library (F. E. Robbins dịch)',
    edition: 'Harvard University Press 1940',
    publicationYear: 150,
    url: 'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ptolemy/Tetrabiblos/home.html',
    sourceLevel: 'S0',
    tradition: 'Hellenistic / Classical Astrology',
    school: 'Classical Ptolemaic',
    language: 'grc / en',
    accessDate: '2026-10-07',
    notes: 'Văn bản nền tảng của chiêm tinh học phương Tây về phẩm tính hành tinh, góc chiếu, và vương vị.',
  },
  {
    sourceId: 'SRC_ASTRO_HAND_1976',
    domain: 'astrology',
    title: 'Planets in Signs & Planets in Aspect',
    author: 'Robert Hand',
    publisher: 'Whitford Press / Para Research',
    publicationYear: 1976,
    sourceLevel: 'S1',
    tradition: 'Western Psychological & Traditional Synthesis',
    school: 'Modern Humanistic Astrology',
    language: 'en',
    accessDate: '2026-10-07',
    notes: 'Khảo luận tiêu chuẩn và chính xác nhất về ý nghĩa hành tinh tại các cung và góc chiếu hình học.',
  },
  {
    sourceId: 'SRC_ASTRO_FORREST_1984',
    domain: 'astrology',
    title: 'The Inner Sky: How to Make Wiser Choices for a More Fulfilling Life',
    author: 'Steven Forrest',
    publisher: 'Seven Paws Press',
    publicationYear: 1984,
    sourceLevel: 'S2',
    tradition: 'Evolutionary Astrology',
    school: 'Modern Evolutionary',
    language: 'en',
    accessDate: '2026-10-07',
    notes: 'Trường phái chiêm tinh tiến hóa nhấn mạnh sự lựa chọn có ý thức và bài học trưởng thành.',
  },
];
