import { SourceRecord } from '../types/source.js';

export const NUMEROLOGY_SOURCES: SourceRecord[] = [
  {
    sourceId: 'SRC_NUM_PYTHAGORAS',
    domain: 'numerology',
    title: 'The Theology of Arithmetic (Theologoumena Arithmeticae)',
    author: 'Pseudo-Iamblichus / Robin Waterfield dịch',
    publisher: 'Phanes Press',
    publicationYear: 350,
    sourceLevel: 'S0',
    tradition: 'Classical Pythagoreanism / Neoplatonism',
    school: 'Greek Arithmology',
    language: 'grc / en',
    accessDate: '2026-10-07',
    notes: 'Triết học số học Hy Lạp cổ đại (Monad đến Decad) khảo cứu bản thể học, không gán bói toán hiện đại.',
  },
  {
    sourceId: 'SRC_NUM_CAMPBELL_1931',
    domain: 'numerology',
    title: 'Your Days Are Numbered: A Manual of Numerology',
    author: 'Florence Campbell',
    publisher: 'The Gateway, New York',
    publicationYear: 1931,
    sourceLevel: 'S1',
    tradition: 'Modern Western Numerology',
    school: 'Pythagorean System Modern',
    language: 'en',
    accessDate: '2026-10-07',
    notes: 'Văn bản trường phái chuẩn hóa hệ số quy đổi chữ cái Pythagoras (1-9) và các chỉ số Đường Đời.',
  },
  {
    sourceId: 'SRC_NUM_GOODWIN',
    domain: 'numerology',
    title: 'Numerology: The Complete Guide (Volumes 1 & 2)',
    author: 'Matthew Oliver Goodwin',
    publisher: 'Newcastle Publishing / CRCS Publications',
    publicationYear: 1981,
    sourceLevel: 'S2',
    tradition: 'Modern Western Numerology',
    school: 'Goodwin Analytical Numerology',
    language: 'en',
    accessDate: '2026-10-07',
    notes: 'Hệ thống công thức quy chuẩn, tính đỉnh cao, thử thách, nợ nghiệp và ma trận tương hợp số học.',
  },
];
