import { SourceRecord } from '../types/source.js';

export const TAROT_SOURCES: SourceRecord[] = [
  {
    sourceId: 'SRC_TAROT_WAITE_1911',
    domain: 'tarot',
    title: 'The Pictorial Key to the Tarot: Being Fragrance of the Greater and Lesser Arcana',
    author: 'Arthur Edward Waite',
    publisher: 'William Rider & Son, London',
    edition: 'Original 1911 Edition',
    publicationYear: 1911,
    url: 'https://archive.org/details/pictorialkeytota00wait',
    sourceLevel: 'S0',
    tradition: 'Western Hermetic / Golden Dawn',
    school: 'Rider-Waite-Smith (RWS)',
    language: 'en',
    accessDate: '2026-10-07',
    notes: 'Văn bản thẩm quyền gốc nền tảng cho 78 lá bài RWS do Pamela Colman Smith minh họa.',
  },
  {
    sourceId: 'SRC_TAROT_MATHERS_1888',
    domain: 'tarot',
    title: 'The Tarot: Its Occult Signification, Use in Fortune-Telling, and Method of Play',
    author: 'S. L. MacGregor Mathers',
    publisher: 'George Redway, London',
    publicationYear: 1888,
    sourceLevel: 'S1',
    tradition: 'Hermetic Order of the Golden Dawn',
    school: 'Golden Dawn Esoteric',
    language: 'en',
    accessDate: '2026-10-07',
    notes: 'Tài liệu nền tảng phân định biểu tượng nguyên tố và hoàng đạo cho hệ thống bài Tarot.',
  },
  {
    sourceId: 'SRC_TAROT_POLLACK_1980',
    domain: 'tarot',
    title: 'Seventy-Eight Degrees of Wisdom: A Book of Tarot',
    author: 'Rachel Pollack',
    publisher: 'Aquarian Press',
    edition: 'Revised Edition 1997',
    publicationYear: 1980,
    sourceLevel: 'S2',
    tradition: 'Modern Psychological Tarot',
    school: 'Archetypal / Psychological RWS',
    language: 'en',
    accessDate: '2026-10-07',
    notes: 'Tác phẩm đối chiếu giải nghĩa tâm lý học chuyên sâu dựa trên khung Rider-Waite-Smith.',
  },
];
