import { SourceRecord } from '../types/source.js';

export const TUVI_SOURCES: SourceRecord[] = [
  {
    sourceId: 'SRC_TUVI_DAO_TANG',
    domain: 'tuvi',
    title: 'Chính Thống Đạo Tạng: Tử Vi Đẩu Số (正統道藏 - 紫微斗數)',
    author: 'Khuyết danh (Tương truyền Trần Đoàn)',
    edition: 'Minh Chính Thống bản (1444-1445)',
    publicationYear: 1445,
    url: 'https://ctext.org/wiki.pl?if=gb&res=662580',
    sourceLevel: 'S0',
    tradition: 'Đạo Giáo Bắc Tống / Minh Triều',
    school: 'Chính Thống Cổ Thư',
    language: 'lzh',
    accessDate: '2026-10-07',
    notes: 'Bản văn cổ được lưu trữ trong Đạo Tạng, nguồn gốc nền tảng của quy cách an sao và luận đoán cổ.',
  },
  {
    sourceId: 'SRC_TUVI_TOAN_THU',
    domain: 'tuvi',
    title: 'Tử Vi Đẩu Số Toàn Thư (紫微斗數全書)',
    author: 'La Hồng Tiên (La Niệm Am) biên soạn',
    publisher: 'Khắc bản đời Minh / Thanh',
    edition: 'Cổ bản mộc bản',
    publicationYear: 1550,
    sourceLevel: 'S1',
    tradition: 'Tử Vi Cổ Điển',
    school: 'Nam Phái Toàn Thư',
    language: 'lzh',
    accessDate: '2026-10-07',
    notes: 'Thư tịch chuẩn hệ thống hóa 14 chính tinh, cách cục, phú đoán miếu vượng đắc hãm.',
  },
  {
    sourceId: 'SRC_TUVI_TRUNG_CHAU_VUONG_DINH_CHI',
    domain: 'tuvi',
    title: 'Trung Châu Phái Tử Vi Đẩu Số Sơ Cấp & Tinh Diệu Phú',
    author: 'Vương Đình Chi',
    publisher: 'Đại Hồn Xuất Bản Xã, Hong Kong',
    publicationYear: 1985,
    sourceLevel: 'S2',
    tradition: 'Trung Châu Phái',
    school: 'Trung Châu Môn',
    language: 'zh / vi',
    accessDate: '2026-10-07',
    notes: 'Hệ thống hóa tinh diệu, tổ hợp sao và tứ hóa theo truyền thừa Trung Châu.',
  },
];
