import { AtomicClaim } from '../types/claim.js';

export const ASTROLOGY_CLAIMS: AtomicClaim[] = [
  {
    claimId: 'CLM_ASTRO_SUN_ARIES_001',
    sourceId: 'SRC_ASTRO_HAND_1976',
    domain: 'astrology',
    subject: 'Mặt Trời tại Bạch Dương',
    predicate: 'radiates',
    object: 'initiating_vitality_and_pioneering_autonomy',
    polarity: 'supportive',
    quotation: 'Direct, forceful energy, pioneering spirit, desire to be first.',
    paraphrase: 'Bản lĩnh tiên phong, trực diện, giàu năng lượng thúc đẩy hành động mở đường.',
    location: { chapter: 'Sun in Signs', page: '28-32' },
    sourceConfidence: 0.95,
  },
  {
    claimId: 'CLM_ASTRO_MOON_TAURUS_001',
    sourceId: 'SRC_ASTRO_HAND_1976',
    domain: 'astrology',
    subject: 'Mặt Trăng tại Kim Ngưu (Vượng Địa / Exaltation)',
    predicate: 'anchors',
    object: 'emotional_stability_and_sensory_groundedness',
    polarity: 'supportive',
    quotation: 'Calm, patient emotional nature, seeks comfort and material stability.',
    paraphrase: 'Tâm thái ổn định vững vàng, nhẫn nại, có nhu cầu sâu sắc về sự an toàn và bền vững.',
    location: { chapter: 'Moon in Signs', page: '55-58' },
    sourceConfidence: 0.95,
  },
  {
    claimId: 'CLM_ASTRO_SATURN_SQUARE_001',
    sourceId: 'SRC_ASTRO_PTOLEMY_TETRABIBLOS',
    domain: 'astrology',
    subject: 'Sao Thổ tạo góc Vuông (Square 90°)',
    predicate: 'restrains',
    object: 'expansion_requiring_rigorous_discipline_and_patience',
    polarity: 'challenging',
    quotation: 'Saturn brings chilling, restriction, delay requiring endurance and rectitude.',
    paraphrase: 'Đòi hỏi kỷ luật nghiêm khắc, chấp nhận độ trễ thời gian và tôi luyện sức chịu đựng.',
    location: { chapter: 'Book I', section: 'Of the Nature of the Planets' },
    sourceConfidence: 0.95,
  },
  {
    claimId: 'CLM_ASTRO_JUPITER_TRINE_001',
    sourceId: 'SRC_ASTRO_HAND_1976',
    domain: 'astrology',
    subject: 'Mộc Tinh tạo góc Tam Hợp (Trine 120°)',
    predicate: 'facilitates',
    object: 'harmonic_expansion_grace_and_philosophical_growth',
    polarity: 'supportive',
    quotation: 'Easy flow of abundance, generosity of spirit, optimism.',
    paraphrase: 'Dòng chảy cơ hội hanh thông, tầm nhìn phóng khoáng và sự nâng đỡ quý giá.',
    location: { chapter: 'Planets in Aspect', page: '210-215' },
    sourceConfidence: 0.95,
  },
  {
    claimId: 'CLM_ASTRO_EARTH_ELEMENT_001',
    sourceId: 'SRC_ASTRO_PTOLEMY_TETRABIBLOS',
    domain: 'astrology',
    subject: 'Nguyên tố Đất (Earth Element: Kim Ngưu, Xử Nữ, Ma Kết)',
    predicate: 'provides',
    object: 'material_stability_pragmatism_and_containment',
    polarity: 'supportive',
    quotation: 'The earth is cold and dry, firm, steady and stabilizing.',
    paraphrase: 'Đặc tính kiên định, thực tiễn, tạo cấu trúc vững chãi và điểm tựa an toàn.',
    location: { chapter: 'Book I', section: 'Of the Four Elements' },
    sourceConfidence: 0.95,
  },
  {
    claimId: 'CLM_ASTRO_MARS_SQUARE_001',
    sourceId: 'SRC_ASTRO_HAND_1976',
    domain: 'astrology',
    subject: 'Hỏa Tinh tạo góc Vuông (Square 90°)',
    predicate: 'generates',
    object: 'impulsive_tension_and_combative_drive',
    polarity: 'challenging',
    quotation: 'Inner tension seeking release through competitive or combative struggle.',
    paraphrase: 'Xung lực căng thẳng đòi hỏi định hướng năng lượng vào hành động kỷ luật thay vì xung đột.',
    location: { chapter: 'Planets in Aspect', page: '145-150' },
    sourceConfidence: 0.92,
  },
];
