import { AtomicClaim } from '../types/claim.js';

export const NUMEROLOGY_CLAIMS: AtomicClaim[] = [
  {
    claimId: 'CLM_NUM_LP1_001',
    sourceId: 'SRC_NUM_GOODWIN',
    domain: 'numerology',
    subject: 'Đường Đời Số 1 (Life Path 1)',
    predicate: 'embodies',
    object: 'independent_leadership_and_original_initiative',
    polarity: 'supportive',
    quotation: 'Pioneering, individuality, self-reliance, leadership.',
    paraphrase: 'Tinh thần độc lập tự chủ, ý chí sáng lập và khát vọng dẫn đầu trong lĩnh vực chuyên môn.',
    location: { chapter: 'Chapter 3: The Life Path', page: '42-47' },
    sourceConfidence: 0.95,
  },
  {
    claimId: 'CLM_NUM_LP5_001',
    sourceId: 'SRC_NUM_GOODWIN',
    domain: 'numerology',
    subject: 'Đường Đời Số 5 (Life Path 5)',
    predicate: 'pursues',
    object: 'adaptability_versatility_and_freedom_of_experience',
    polarity: 'supportive',
    quotation: 'Freedom, adaptability, variety, progress through curiosity.',
    paraphrase: 'Khát khao trải nghiệm đa diện, linh hoạt biến chuyển và phản kháng sự gò bó cứng nhắc.',
    location: { chapter: 'Chapter 3: The Life Path', page: '65-71' },
    sourceConfidence: 0.95,
  },
  {
    claimId: 'CLM_NUM_LP4_001',
    sourceId: 'SRC_NUM_CAMPBELL_1931',
    domain: 'numerology',
    subject: 'Đường Đời Số 4 (Life Path 4)',
    predicate: 'constructs',
    object: 'methodical_foundations_and_pragmatic_order',
    polarity: 'supportive',
    quotation: 'The builder, stability, methodical application, duty.',
    paraphrase: 'Xây dựng nền tảng vững chắc, tôn trọng quy chuẩn, trật tự và sự cẩn trọng kiên định.',
    location: { chapter: 'The Primary Vibration 4', page: '38-42' },
    sourceConfidence: 0.95,
  },
  {
    claimId: 'CLM_NUM_KARMIC_16_001',
    sourceId: 'SRC_NUM_GOODWIN',
    domain: 'numerology',
    subject: 'Số Nợ Nghiệp 16/7 (Karmic Debt 16/7)',
    predicate: 'demands',
    object: 'dissolution_of_ego_and_spiritual_reorientation',
    polarity: 'challenging',
    quotation: 'Breakdown of pride and false illusions to find true higher values.',
    paraphrase: 'Sự thanh lọc bản ngã và ảo tưởng vật chất nhằm tái định hướng vào chiều sâu nội tâm.',
    location: { chapter: 'Special Modifiers: Karmic Debts', page: '198-204' },
    sourceConfidence: 0.9,
  },
  {
    claimId: 'CLM_NUM_MASTER_11_001',
    sourceId: 'SRC_NUM_GOODWIN',
    domain: 'numerology',
    subject: 'Số Bậc Thầy 11/2 (Master Number 11)',
    predicate: 'channels',
    object: 'heightened_intuitive_illumination_and_idealism',
    polarity: 'supportive',
    quotation: 'Illumination, inspiration, nervous sensitivity requiring grounding.',
    paraphrase: 'Trực giác nhạy bén, khả năng truyền cảm hứng sâu sắc đi kèm áp lực căng thẳng thần kinh.',
    location: { chapter: 'Master Numbers', page: '115-122' },
    sourceConfidence: 0.95,
  },
];
