import { AtomicClaim } from '../types/claim.js';

export const TAROT_CLAIMS: AtomicClaim[] = [
  {
    claimId: 'CLM_TAROT_FOOL_001',
    sourceId: 'SRC_TAROT_WAITE_1911',
    domain: 'tarot',
    subject: 'The Fool',
    predicate: 'represents',
    object: 'state_of_pure_potentiality_and_spiritual_quest',
    polarity: 'supportive',
    quotation: 'He is the spirit in search of experience... His gestures suggest a swift movement of the body.',
    paraphrase: 'Khai mở hành trình trải nghiệm linh hồn với tâm thái tự do thuần khiết và niềm tin tuyệt đối.',
    location: { chapter: 'Part II: The Doctrine Behind the Veil', page: 'The Fool' },
    sourceConfidence: 1.0,
  },
  {
    claimId: 'CLM_TAROT_MAGICIAN_001',
    sourceId: 'SRC_TAROT_WAITE_1911',
    domain: 'tarot',
    subject: 'The Magician',
    predicate: 'manifests',
    object: 'conscious_will_directing_universal_elements',
    polarity: 'supportive',
    quotation: 'Signifies the divine motive in man, reflecting God, the will in the liberation of its activities.',
    paraphrase: 'Năng lực vận dụng ý chí và công cụ thực tế để hiện thực hóa ý niệm thành kết quả rõ ràng.',
    location: { chapter: 'Part II', page: 'The Magician' },
    sourceConfidence: 1.0,
  },
  {
    claimId: 'CLM_TAROT_7P_001',
    sourceId: 'SRC_TAROT_WAITE_1911',
    domain: 'tarot',
    subject: 'Seven of Pentacles',
    predicate: 'signifies',
    object: 'deliberate_pause_for_evaluating_accumulated_work',
    polarity: 'neutral',
    quotation: 'A young man leaning on his staff and looking intently at seven pentacles... pause in work.',
    paraphrase: 'Khoảng lặng có chủ đích để thẩm định thành quả vun trồng trước khi quyết định bước tiếp.',
    location: { chapter: 'Part III: The Outer Method of the Oracles', section: 'Pentacles' },
    sourceConfidence: 0.95,
  },
  {
    claimId: 'CLM_TAROT_DEATH_001',
    sourceId: 'SRC_TAROT_WAITE_1911',
    domain: 'tarot',
    subject: 'Death',
    predicate: 'denotes',
    object: 'inevitable_transformation_and_cessation_of_old_forms',
    polarity: 'challenging',
    quotation: 'The veil or outward sign which gives reason to call it the end of all.',
    paraphrase: 'Sự chấm dứt tất yếu của chu kỳ cũ để nhường chỗ cho tiến trình tái sinh và tái cấu trúc.',
    location: { chapter: 'Part II', page: 'Death' },
    sourceConfidence: 1.0,
  },
  {
    claimId: 'CLM_TAROT_TOWER_001',
    sourceId: 'SRC_TAROT_WAITE_1911',
    domain: 'tarot',
    subject: 'The Tower',
    predicate: 'shatters',
    object: 'false_structures_and_illusion_of_material_security',
    polarity: 'challenging',
    quotation: 'Ruin of the House of We and breakdown of false beliefs by light.',
    paraphrase: 'Sự sụp đổ bất ngờ của cấu trúc ảo tưởng nhằm giải phóng sự thật cốt lõi.',
    location: { chapter: 'Part II', page: 'The Tower' },
    sourceConfidence: 1.0,
  },
];
