import { AtomicClaim } from '../types/claim.js';

export const TUVI_CLAIMS: AtomicClaim[] = [
  {
    claimId: 'CLM_TUVI_TUVI_MENH_001',
    sourceId: 'SRC_TUVI_TOAN_THU',
    domain: 'tuvi',
    subject: 'Sao Tử Vi tại Mệnh',
    predicate: 'endows',
    object: 'leadership_dignity_and_authoritative_rectitude',
    polarity: 'supportive',
    quotation: 'Tử Vi đế tọa, tính tình đôn hậu, đoan chính, uy nghi, có năng lực thống lĩnh.',
    paraphrase: 'Khí chất bậc lãnh đạo, đĩnh đạc, tự chủ và giàu lòng tự tôn.',
    location: { chapter: 'Đẩu Số Quy Quy', section: 'Tử Vi Tinh Diệu Ca' },
    sourceConfidence: 0.95,
  },
  {
    claimId: 'CLM_TUVI_THIENCO_001',
    sourceId: 'SRC_TUVI_TOAN_THU',
    domain: 'tuvi',
    subject: 'Sao Thiên Cơ tại Mệnh',
    predicate: 'manifests',
    object: 'adaptability_tactical_intellect_and_agile_planning',
    polarity: 'supportive',
    quotation: 'Thiên Cơ vi thiện tinh, mưu trí linh hoạt, thích động không thích tĩnh.',
    paraphrase: 'Tư duy cơ biến, nhạy bén tính toán phương án và thích nghi cao độ với hoàn cảnh.',
    location: { chapter: 'Đẩu Số Quy Quy', section: 'Thiên Cơ Luận' },
    sourceConfidence: 0.95,
  },
  {
    claimId: 'CLM_TUVI_THATHAT_HAM_001',
    sourceId: 'SRC_TUVI_TRUNG_CHAU_VUONG_DINH_CHI',
    domain: 'tuvi',
    subject: 'Thất Sát hãm địa hoặc ngộ Kình Đà',
    predicate: 'triggers',
    object: 'volatility_impatience_and_arduous_struggle',
    polarity: 'challenging',
    quotation: 'Thất Sát hãm địa hội Sát tinh, tính cương cấp bạo bức, dễ gặp trắc trở.',
    paraphrase: 'Sự nóng vội và quyết liệt quá mức dẫn tới biến động mạnh trong giai đoạn khai phá.',
    location: { chapter: 'Chương 4: Sát Tinh Tinh Diệu Phối Hợp', page: '98-102' },
    sourceConfidence: 0.9,
  },
  {
    claimId: 'CLM_TUVI_HOALOC_MENH_001',
    sourceId: 'SRC_TUVI_TOAN_THU',
    domain: 'tuvi',
    subject: 'Hóa Lộc nhập Mệnh/Tài',
    predicate: 'enhances',
    object: 'resource_attraction_and_harmonious_enterprise',
    polarity: 'supportive',
    quotation: 'Lộc nhập tài bạch vi hanh thông, sinh cơ phát triển.',
    paraphrase: 'Gia tăng nguồn lực tài chính, cơ hội hợp tác và năng lượng hanh thông.',
    location: { chapter: 'Tứ Hóa Luận Đoán', section: 'Hóa Lộc Chi Diệu' },
    sourceConfidence: 0.95,
  },
  {
    claimId: 'CLM_TUVI_HOAKY_001',
    sourceId: 'SRC_TUVI_TRUNG_CHAU_VUONG_DINH_CHI',
    domain: 'tuvi',
    subject: 'Hóa Kỵ nhập Mệnh hoặc Tật Ách',
    predicate: 'signals',
    object: 'karmic_entanglement_obsessive_worry_and_friction',
    polarity: 'challenging',
    quotation: 'Hóa Kỵ chủ thị phi, tâm đa trăn trở, cần tu tâm nhẫn nại.',
    paraphrase: 'Điểm thắt tâm lý, vướng bận suy nghĩ nội tâm và đòi hỏi sự thấu suốt để chuyển hóa.',
    location: { chapter: 'Chương 8: Tứ Hóa Bí Điển', page: '185-190' },
    sourceConfidence: 0.92,
  },
];
